### DISCUSSION TITLE
Clarify how to handle default value on non-nullable optional properties when "default" keyword is not specified

### DISCUSSION THREAD

**Discussion by ahmednfwela** [OAI/OpenAPI-Specification#2807] [Q&A]
Related https://github.com/OpenAPITools/openapi-generator/issues/10972

Spec version: 3.0.3
the spec doesn't indicate how to handle model properties in the following case:
```yaml
required: false
nullable: false
type: xxxxx
```
- `required: false` means that the property might not exist in the json
- `nullable: false` means that the property doesn't accept null as a value

so what to do when the spec document doesn't specify the `default` keyword ?

1.  assume default is null (works only for properties where `nullable: true`, [otherwise it will break the spec](https://swagger.io/specification/#:~:text=default%20%2D%20The%20default,cannot%20be%201.))

2. assume default to be of same type as type, so for non-nullable types that would be
  "boolean" => false
  "object" => { }
  "array" => [ ]
  "number"/"integer" => 0
  "string" => ""

3. make it required to specify the `default` keyword when `required: false` and `nullable: false`
4. ignore the provided `required: false` and assume instead `required: true`
5. ignore the provided `nullable: false` and assume `nullable: true`

**Comment by webron** [comment]
Not sure I follow the issue here (and I tried checking the linked issue as well). Why is the `default` relevant at all in this case? If it doesn't exist, there's just no default value. It doesn't affect what kind of type is supported.

**Reply by hkosova** [reply]
@webron Example: given this schema
```yaml
type: object
required: [foo]
properties:
  foo:
    type: string
  bar:       # <--- Optional property without a default value defined
    type: string
```
and the payload `{"foo": "test"}`, what value for `bar` should the consumer of this payload assume when deserializing this payload?
