### DISCUSSION TITLE
When using OAuth 2.0, how do you describe the exact mechanism that should be used to authorize requests to a resource server?

### DISCUSSION THREAD

**Discussion by alex-feel** [OAI/OpenAPI-Specification#2867] [Q&A]
OpenAPI allows you to specify an OAuth security scheme type and a list of scopes required to request an endpoint (resource server). It might look like this:

```
components:
  securitySchemes:
    oAuthSample:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://api.example.com/oauth2/authorize
          scopes:
            read_pets: read pets in your account
            write_pets: modify pets in your account
```

```
paths:
  /pets/{petId}:
    patch:
      summary: Updates a pet in the store
      security: 
        - oAuthSample: [write_pets]
      ...
```

Source: https://swagger.io/docs/specification/authentication/oauth2/.

How, from such a specification, you can understand how exactly a client should be authorized on a resource server on behalf of an user? Should it just be stated in a text documentation, or is there a standardized way provided by OpenAPI?

Or maybe it's better to formulate the question as follows - how in OpenAPI to specify the type of an access token from the options defined here https://www.iana.org/assignments/oauth-parameters/oauth-parameters.xhtml#token-types, that is issued by an authorization server and, as a result, explain how the token is used for authorization on a resource server?

P.S. This question was originally asked on [Stackoverflow](https://stackoverflow.com/questions/70867784/in-openapi-when-using-oauth-2-0-how-do-you-describe-the-exact-mechanism-that-s).
