### DISCUSSION TITLE
Can you define placeholders to replace in component schemas?

### DISCUSSION THREAD

**Discussion by Andre601** [OAI/OpenAPI-Specification#3004] [Q&A] [answered]
I'm interested in creating an OpenAPI specification for my Rest API, but one thing that bothers me is the defining of responses for the API.

My API has 2 specific JSON replies based on HTTP response codes:

- `200`
  ```json
  {
    "error": false,
    "link": "https://example.com/img/animals/cat/cat_001.jpg",
    "time": 0
  }
  ```
- `403` or `404`
  The info is mostly the same, with the exception of the `message` being different. Example with an invalid path (403) is shown here.
  ```json
  {
    "details": {
      "path": "/api/invalid/path",
      "content-type": "application/json",
      "user-agent": "Some-UA/1.0"
    },
    "error": true,
    "message": "The provided path is not valid.",
    "time": 0
  }
  ```

While I can, for the most part, create two components to cover the 403 and 404 cases, would I like to have an example scheme that depicts an example link matching the provided URL path for the successful request.
If f.e. the path defined is `/api/img/cat/` should the example JSON have a URL pointing to a random cat image (As shown above).

This, to my knowledge, requires me to create a separate scheme for each API endpoint I have if I want to have this.

So my question now is, can I define some kind of placeholder in the scheme, to then be replaced with whatever value I provide?

Like f.e.
```yaml
components:
  schemas:
    image-response-200:
      type: object
      properties:
        error:
          type: boolean
          example: false
        link:
          type: string
          example: "https://example.com/img/{type}/{type}_001.jpg"
        time:
          type: integer
          format: int32
          example: 0
```
would then allow me to provide "cat" as type somewhere and the example shown would have `{type}` replaced with `cat`

I hope such a feature exists, as it would reduce the copy-paste jobs I have by a lot in the end...
