### DISCUSSION TITLE
Include HTTP version (1.1/2/3) in the spec

### DISCUSSION THREAD

**Discussion by rafalkrupinski** [OAI/OpenAPI-Specification#3049] [Enhancements]
The servers are typically backwards compatible so any API client could connect using the lowest version,
but including HTTP versions in the spec would tell a client developer that they can use a special library and connect via the higher version.

I propose something like this:
```yaml
openapi:
    http-versions:
    - '1.0'
    - '1.1'
    - '2.0'
    - '3.0'
```
