### DISCUSSION TITLE
How to define multiple objects to the definitions or components

### DISCUSSION THREAD

**Discussion by BhanuKiranChaluvadi** [OAI/OpenAPI-Specification#3062] [Q&A] [answered]
Hi , 

I have a definition (swagger-2.0)
```
  ErrorCode:
    type: object
    properties:
      code:
        type: integer
      field: 
        type: string 
```

I would like to add possible value for this structure into openapi documentation. Practically, code and field corresponds to the same thing (one in numerical and the other in English). I would like all the possible objects be part of the openAPI document, so the client can translate them into multiple languages if needed.
For example 
```
{
	{
		code: 1001
		field: "missing_file"
	},
	{
		code: 1002
		field: "invalid_file"
	},
	{
		code: 1003
		field: "large_file"
	},
	...
}
```

How to specify all the ErrorCode in the openapi document

**Comment by rafalkrupinski** [comment, marked as answer]
```yaml
ErrorCode:
    type: object
    properties:
      code:
        type: integer
      field: 
        type: string 
    enum:
    - code: 1001
      field: missing_file
    - code: 1002
      field: invalid_file
...
```
