### DISCUSSION TITLE
Refactor of Server url and path

### DISCUSSION THREAD

**Discussion by JRamonMC** [OAI/OpenAPI-Specification#3341] [Q&A] [answered]
Hi all,

My question is related to the server URL and path. Let's assume we have the following specification (I will omit some parameters):
``` yaml
servers: 
   - url: https://fake-environment.com
paths:
   - /cars: # POST - GET
       $ref: paths/cars.yaml 
   - /cars/test1: # GET
       $ref: paths/cars-test1.yaml 
   - /cars/test2: # GET 
       $ref: paths/cars-test2.yaml 
   .... (All paths start with `/cars`)
```

In a refactor, I decide to move `/cars` to the server URL and it looks like this: 

``` yaml
servers: 
   - url: https://fake-environment.com/cars
paths:
    - /: # POST - GET
       $ref: paths/cars.yaml 
   - /test1 : # GET
       $ref: paths/cars-test1.yaml 
   - /test2: # GET
       $ref: paths/cars-test2.yaml 
 ```

However this is a little bit weird, because if I do a POST in the original one, it was POST https://fake-environment.com/cars, but in the new one it will be POST https://fake-environment.com/cars/ . So my question here is: 

- Does it make sense this refactor? 
- Should I rename the first path to `/create` or something like that? This is related to the restriction where all paths must start with `/`.
- Is there any way to avoid that `/` at the end of the path? 

If you need more explanation, please let me know. 

Thanks in advance!!!
