### DISCUSSION TITLE
Treatment of trailing forward slash on Server Object "url".

### DISCUSSION THREAD

**Discussion by charjr** [OAI/OpenAPI-Specification#3512] [Q&A] [answered]
If you had something like this:
```yaml
# rest of api...
servers:
  - url: http://petstore.swagger.io/
paths:
  /pets:
    get:
# rest of api...
```

Assuming no other servers are specified at any level; what would the expected url be for a `get` request to `/pets`?

`https://petstore.swagger.io/pets`
or
`https://petstore.swagger.io//pets`
