### DISCUSSION TITLE
How to define Header parameter values?

### DISCUSSION THREAD

**Discussion by jeremyfiel** [OAI/OpenAPI-Specification#3827] [Q&A]
I've not found any sufficient way to define header parameter values such as below: 

- `rel` in a `link` header 
- `q` in an `accept` header
- `name` in `content-disposition` header
- cache directives
etc...

Can someone share an example of that?

**Comment by handrews** [comment]
@jeremyfiel modeling headers is a [major weakness](https://github.com/OAI/OpenAPI-Specification/issues?q=is%3Aissue+is%3Aopen+label%3Aheaders) in 3.x.  The `schema`/`style`-based approach is rarely suitable because it implies RFC6570 percent-encoding, which is rarely appropriate for headers.  The `content` approach pretty much boils down to defining a `text/plain` representation and doing all of the work yourself (the `pattern` keyword won't get you very far).

We're looking at modeling HTTP interactions more holistically, including headers, in Moonwalk, and I'm hopeful that we could backport the header chunk to a 3.3 (if we can get approval for a 3.3, which would depend on a small, successful 3.2).

A few thoughts on your specific questions:

* `rel` in a `link` header:  #667 
* `q` in an `accept` header: in theory, the key under `content` is a media range, which can include the `q` parameter (`Accept` takes a media range)- would that help?  I figure the set of media ranges under `content` defines the valid `Accept` options although that's certainly not stated anywhere
* `name` in `content-disposition` header: do you need to do that outside of `multipart/form-data`?  Are you [using it with `multipart/mixed`](https://github.com/OAI/OpenAPI-Specification/issues/3721#issuecomment-2119378189)?
* cache directives: #2784 

See also (which I somehow forgot but @jeremyfiel noticed):

* #2458

**Comment by jeremyfiel** [comment]
I'll pat myself on the back for this one.. I did indeed find and read all of your links prior to posting. 😃 

regarding the `media-range` usage, i'm not interested in the `media-range` value, but rather the `weight` value which is the `q`.  How would the media-range in `content` include the `q` parameter? 

```yaml
compenents:
  parameters:
    accept:
      name: accept
      in: header
      content:
        'application/json; q=0.9': // like this??? This doesn't allow any definition of the `q` value though. Where would a user manually input a `q` value in a UI, specifically to test different `q` values and the response they may receive. 
          schema:
            type: string
        'application/vnd.app+json; q=0.8':
          schema:
            type: string
        'application/vnd.another_app+json; q=0.6':
          schema:
            type: string
```
Imagine you have multiple mediatypes available and you want to rank their preference, that doesn't work to define the value of `q` or `charset` or any other parameter value after the `media-range`.

A good example from RFC9110 shows the behavior we are unable to define in OAS3.x.x. 
> Accept: audio/*; q=0.2, audio/basic
is interpreted as "I prefer audio/basic, but send me any audio type if it is the best available after an 80% markdown in quality".


setting these parameters for something like `accept` might seem unnecessary, but i'm more interested in some other headers and their parameters like `content-disposition`(name, filename) and `link` (rel).  We use many different `rel` values in a `link` header and would like to define those for our consumers. 

Yes, we are using `content-disposition` in `multipart/mixed` and would like to define some of those parameter values.
