### DISCUSSION TITLE
As per OAS, when defining discriminator with explicit mapping, should implicit discriminator value still be accepted?

### DISCUSSION THREAD

**Discussion by ondrej-simon** [OAI/OpenAPI-Specification#3918] [Q&A] [answered]
Hi, I have not found any information about this in the documentation (potential hint for extension), so I am asking here.

Let's say I have the following schema which explicitly defines mapping for `Bar` and `Baz` objects:

```yaml
Foo:
  type: object
  discriminator:
    propertyName: type
    mapping:
      BAR: '#/components/schemas/Bar'
      BAZ: '#/components/schemas/Baz'
  required:
    - type
  properties:
    type:
      type: string
```

I know that when a discriminator is not present, an implicit mapping is to be considered to aid (de)serialization, in this case `type: Bar` would map to `Bar`, and `type: Baz` would map to `Baz`.

But when I define explicit mapping, should the implicit value still be allowed, or should the API accept only the manually specified options?
