### DISCUSSION TITLE
Clarification Needed on Path Template Normalization in Find Function for Swagger Document Generation

### DISCUSSION THREAD

**Discussion by dwertent** [OAI/OpenAPI-Specification#4036] [Q&A]
Could you clarify the rationale behind [normalizing path templates](https://pkg.go.dev/github.com/getkin/kin-openapi@v0.127.0/openapi3#Paths.Find) in the `Find` function? Specifically, in cases where different paths use similar templates (like `{iid}` and `{did}`), is normalization intended to handle such scenarios? We're evaluating whether this behavior is essential for Swagger document generation, and understanding its original purpose would help us decide if and when normalization makes sense.

Here is an example of the expected document:
```
  /identities/{iid}:
    get:
      description: Gets an identity by its ID
      operationId: getIdentityByID
      parameters:
      - description: The identity ID 
        in: path
        name: iid
        required: true
        schema:
          example: id
          type: string
       ...
  /identities/{did}:
    get:
      description: Gets an identity by its DID
      operationId: getIdentityByDID
      parameters:
      - description: The identity DID 
        in: path
        name: did
        required: true
        schema:
          example: did
          type: string
        ...
```
