### ISSUE TITLE
 Swagger doc for properties that are dynamically generated and their types are also not the same.

### ISSUE THREAD

**Issue by anupamaj83** [OAI/OpenAPI-Specification#1018]
I have a use case where the labels for a model's properties are dynamically generated from object to object and their types are also not the same. Any idea how to go about documenting this in Swagger2.0? Thanks!

```
e.g.: Object 1:
        form: 
          properties: 
            pl_ui: 
              properties: 
                environment: 
                  properties: 
                    BYPASS_SECURITY: 
                      type: "string"
                    NODE_ENV: 
                      type: "string"
                    ACCOUNT_MANAGEMENT_HOST: 
                      type: "string"
                    ACCOUNT_MANAGEMENT_PORT: 
                      type: "string"
                  type: "object"
              type: "object"
          type: "object"


Object 2:
        form: 
          properties: 
            es_search: 
              properties: 
                resources: 
                  properties: 
                    limits: 
                      properties: 
                        cpu: 
                          type: "number"
                        memory: 
                          type: "number"
                      type: "object"
                    requests: 
                      properties: 
                        cpu: 
                          type: "number"
                        memory: 
                          type: "number"
                      type: "object"
                  type: "object"
                config: 
                  properties: {}
                  type: "object"
              type: "object"
          type: "object"

object 3:
        form: 
          properties: 
            work-ui: 
              properties: 
                resources: 
                  properties: 
                    limits: 
                      properties: 
                        memory: 
                          type: "number"
                        cpu: 
                          type: "number"
                      type: "object"
                    requests: 
                      properties: 
                        memory: 
                          type: "number"
                        cpu: 
                          type: "number"
                      type: "object"
                  type: "object"
                environment: 
                  properties: 
                    BYPASS_WSS_SEC: 
                      type: "string"
                  type: "object"
              type: "object"
```
