### ISSUE TITLE
Rename `bearerFormat` to `format`, allow it to be used by others, with jwt | opague | text

### ISSUE THREAD

**Issue by shiup** [OAI/OpenAPI-Specification#1043]
In the `Security Scheme Object`, the `bearerFormat` is very limited, value is string, and only applies to the OAuth.

Can this be more generic by changing the term to `format` and allow it to be used for all other security options (given it is for information only).  This way, we can use it for `apiKey` for example.

**Comment by darrelmiller** [comment]
You have complete flexibility using just the `http` type.

```json
{
  "type": "http",
  "scheme": "whatever-you-want",
}
```
Now you can make http requests using the `Authorization` header with the scheme `whatever-you-want` and add whatever auth parameters you want.
The only reason for the bearerFormat property is because the `bearer` scheme doesn't actually tell you anything about the token https://tools.ietf.org/html/rfc6750#section-1.2  This is usually because you get it from a token server and the client doesn't really need to know the format.

**Comment by shiup** [comment]
Can you elaborate on how that can be done with http type ?  http is protocol.. 
So in the scenario, I have 2 apiKey..
```
securityDefinitions:
  api-key-1:
    type: apiKey
    description: test
    in: header
    name: id
  api-key-2:
    type: apiKey
    description: test
    in: header
    name: key
```
for `id` check, I would like to do a `db1` lookup.
for `key` check, I would like to do a `db2` lookup.
However, the `name` should be flexible enough.. so `id` -> `myid`, and `key` -> `foo`.  So it needs to have a way to indicate `api-key-1` is *type* `lookupwithdb1`, and `api-key-2` is *type* `lookupwithdb2`.

How will the above solved with the `http` type ?  What it is also confusing, what other type are there ?  tx.
