### ISSUE TITLE
Template parameters not allowed in query part of URL (OpenSearch-like)

### ISSUE THREAD

**Issue by ycespb** [OAI/OpenAPI-Specification#1054]
Dear all,
I have to say first of all that the specification is very interesting (we only discovered it recently) and we are looking forward for tool support to be aligned with this new version and apply it in current and future projects.

I wonder if the OAI specification could cover use cases for which today in our domain (Earth Observation) OpenSearch [1] Description Documents (OSDD) are used.  This would require *path templating* also to be allowed in the query part or associating an actual parameter with the OpenSearch parameter.

We are currently relying heavily on OpenSearch 1.1 [1] and Parameter Extension of OpenSearch [2] for defining API, but the tendency now is to migrate this XML-based solution to a JSON equivalent and OAI comes very close...
The OSDD allows for URL templates like
`template="http://example.com/search?q={searchTerms}"`, and only the parameter names between the {} are standardised by OpenSearch or related Open GeoSpatial Consortium specifications such as OGC 10-032r8 or [OGC 13-026r8](http://docs.opengeospatial.org/is/13-026r8/13-026r8.html). Implementations are free to choose actual query parameter names.

For an OpenAPI description to be an alternative for an OSDD, it would be useful to be able to associate the actual query/path parameter names with their OpenSearch definition, thus associate `q` with `searchTerms` in the example.  For the path parameters (`in: path`), this is already possible.  However, for parameters which appear after the "?" (`in: query`), this is not allowed.

Either allowing in OAI to have paths with a query part with template parameters (which is similar to the `x-ms-paths` notation from Microsoft Azur [3]):
```
paths:
/example.com/search?q={searchTerms}&startRecord={startIndex}:
    get:
      parameters:
        - name: searchTerms   // 
          in: path             // this is currently not allowed in the query part of a "Path".
          description: Free text search term {searchTerms}.
          required: false
          type: string 
```

Alternatively, if extending the "path templating" cannot be envisaged, an association between `q` and `searchTerms` as in the OpenSearch Parameter Extension [2] could be done with a property such as `x-value` as below:

```
paths:
/example.com/search:
   get:
      parameters:
        - name: q
          x-value: "{searchTerms}"
          in: query
          description: Free text search term {searchTerms}.
          required: false
          type: string 
```

Another feature on our wishlist is to be able to distinguish values in enumerations (but also normal query parameter) from the way user interfaces would present them to users, e.g.
the Parameter Extension of OpenSearch uses:

```
<param:Option label="NASA Common Metadata Repository" value="EOP:NASA:CMR"/>
```

In OAI, there is no way to associate a "label" and it becomes:

```
          enum:
          - EOP:NASA:CMR
```

Have OpenSearch like "templating" capabilities been considered or could be envisaged?   The current space Earth Observation community (e.g. CEOS [4]) which has invested a lot in the OpenSearch-like technology would then have a clear migration path to JSON/OAI while preserving the effort which went in defining the OpenSearch extensions with specific parameters for this domain....

regards,
Yves.

References used above:
[1]: http://www.opensearch.org/Specifications/OpenSearch/1.1
[2]: http://www.opensearch.org/Specifications/OpenSearch/Extensions/Parameter/1.0/Draft_2
[3]: https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/creating-swagger.md
[4]: http://ceos.org/ourwork/workinggroups/wgiss/access/opensearch/
