### ISSUE TITLE
xml attributes

### ISSUE THREAD

**Issue by FerrariAlberto** [OAI/OpenAPI-Specification#1076]
hello everyone,

i'm trying to create the schema of an object that looks like this

```xml
<order order_id="1111">
      <product>
        ...
      </product>
</order>
```

what i wrote in the swagger editor is this

```definitions:
  order:
    type: array
    xml:
      name: order
      wrapped: true
    items:
      $ref: '#/definitions/product'
    properties:
      order_id:
        type: integer
        example: 1111
        xml:
          attribute: true
```

the swagger editor shows the object correctly but swagger ui ignores everything but the attribute

```xml
<?xml version="1.0" encoding="UTF-8"?>
<order id="1111">
</order>
```

any idea where the problem is?
thank you for any usefull hint

**Comment by FerrariAlberto** [comment]
also how do i write something like this?

```
<model stock_id="3" locked="11" available="5" />
```

i'm trying like this 

```
model:
        type: object
        properties:
          stock_id:
            type: integer
            example: 3
            xml:
              attribute: true
          locked:
            type: integer
            example: 11
            xml:
              attribute: true
          available:
            type: integer
            example: 5
            xml:
              attribute: true
        xml:
          name: model
```

but i'm getting this

```
<model stock_id="3" locked="11" available="5"></model>
```
