### ISSUE TITLE
Unable to reference OpenAPI Specification JSON Schema from HTTPS Site

### ISSUE THREAD

**Issue by mzaferyahsi** [OAI/OpenAPI-Specification#1083]
Hi,

We're displaying OpenAPI Specification on our Developer Portal and our Developer Portal API uses OpenAPI Specification v2.0 to add/update APIs. The issue is when we want to display OpenAPI Specification of our Developer Portal, our parser fails to de-reference the content since it's "not-https" and the links inside it is also "non-https". You can find the YAML of our API.

Can you provide a JSON Schema that we can reference using https?

Thanks.

[http_valid_https_invalid.txt](https://github.com/OAI/OpenAPI-Specification/files/975728/http_valid_https_invalid.txt)

**Comment by RobDolinMS** [comment]
>Can you provide a JSON Schema that we can reference using https?

@mzaferyahsi  What is the JSON Schema that you're referencing using HTTP?

**Comment by ePaul** [comment]
The uploaded file contains this:

```yaml
      parameters:
        - name: X-EXP-AccessToken
          in: header
          required: true
          type: string
        - in: body
          name: openAPI
          required: true
          schema:
            $ref: 'http://json-schema.org/draft-04/schema#'
```
(And again for another operation.) This is the HTTP link we are having here.

@mzaferyahsi  This is wrong – I think the idea is to upload an OpenAPI document here (guessing from the parameter name). The schema reference is the JSON schema for JSON schema documents themselves. You would need to have an OpenAPI schema (which is similar, but not identical to a JSON schema) for an OpenAPI document (which is quite different from a JSON schema, because it contains paths, info etc., not directly a schema).

I am not sure whether it is possible to define an OpenAPI document with an OpenAPI schema – I think that at least version 2.0 is not powerful enough for that. (Of course, you could allow a simple superset of that – something like this:

```yaml
  definitions:
    openAPIdoc:
      type: object
      properties:
        swagger:
          type: string
        info:
          type: string
        ...
        schemes:
          type: array
          items:
            type: string
        ...
        path:
           type: object
        definitions:
           type: object
        ...
     required:
       - info
       - paths
       - swagger
```
(You can go a bit deeper, but you'll hit your limits at several places, e.g. with the parameters in the path item object, which either are references or a parameter objects. OpenAPI 2.0 schemas don't support "or".)

If you still can change your API, I would recommend to a form parameter with `type: file`, and add a description which says what. (I just noted that `type: file` is not allowed for a body parameter in 2.0 ... not sure why.)
If you want to go with a schema, I would recommend something like the thing above, or just `type: object` without anything more.
