### ISSUE TITLE
Operation's Parameter schemas allows nested object schemas?

### ISSUE THREAD

**Issue by slinkydeveloper** [OAI/OpenAPI-Specification#1129]
Is allowed to add a schema like this inside Parameter Object?
```yaml
type: object
properties:
    name:
        type: string
    surname:
        type: string
    aList:
        type: array
        items:
            type: string
        
```
If yes, after the first level of tree, i have to take care about `explode` field? If `explode = true`, what I have to expect in this case?
