### ISSUE TITLE
`callbacks` is a map of Callback Objects.... but why?

### ISSUE THREAD

**Issue by webron** [OAI/OpenAPI-Specification#1141]
The way the `callbacks` property is defined now, this is valid:

```yaml
callbacks:
  callbacks1:
    "{myamazingexpressions}":
      PIO1:...
  callbacks2:
    "{myamazingexpressions}":
      PIO2:...
```
This means that you can define two different Callback Objects, each one having the same expression as a key, pointing to a different POI. That doesn't seem to make sense.

Perhaps callbacks should just be a Callback Object?

**Comment by darrelmiller** [comment]
I believe the idea of multiple distinct callback objects was introduced to support the notion of webhooks returning different "events".  All of the callbacks might target the same client URL but the structure of the payload might be very different.  Now that we have added support for JSON Schema `oneOf` it would be possible to do this with a single `requestBody`.  However, if someone wanted to identify the event in a query parameter or HTTP header, it would not be possible using a single PathItemObject.

e.g.
```yaml
callbacks:
  bankAccountDeposit:
    "{$request.body#/url}&eventType=deposit":
      post: ...
  bankAccountWithdrawal:
    "{$request.body#/url}&eventType=withdrawal":
      post: ...
  bankAccountOverdraft:
    "{$request.body#/url}&eventType=overdraft":
      post: ...
 ```

The question this raises for me is why not do this?

```yaml
callbacks:
  bankAccountEvents:
    "{$request.body#/url}&eventType=deposit":
      post: ...
    "{$request.body#/url}&eventType=withdrawal":
      post: ...
    "{$request.body#/url}&eventType=overdraft":
      post: ...
 ```
This gets a bit more unclear if the event type was not in the query string but in a header or the body and of course the key is no longer unique, which is a bigger problem.

Is this better?

```yaml
callbacks:
  bankAccountDeposit:
    targetUrl: "{$request.body#/url}&eventType=deposit":
    post: ...
  bankAccountWithdrawal:
    targetUrl: "{$request.body#/url}&eventType=withdrawal":
    post: ...
  bankAccountOverdraft:
    targetUrl: "{$request.body#/url}&eventType=overdraft":
    post: ...
 ```
