### ISSUE TITLE
Clarification on comma-separated media types under content

### ISSUE THREAD

**Issue by hkosova** [OAI/OpenAPI-Specification#1282]
In the OpenAPI 3.0 Specification, the [Request Body Object](https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.md#requestBodyObject) section states (emphasis mine):

> content
> Map[string, Media Type Object]
> REQUIRED. The content of the request body. The **key is the media type** and the value describes it.

This reads as if the key must be a single media type. But [further down](https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.md#considerations-for-file-uploads) there's an example with comma-separated media types - `image/png, image/jpeg`.

```
# multiple, specific media types may be specified:
requestBody:
  content:
    'image/png, image/jpeg':
      # a binary file of type png or jpeg
      schema:
        type: string
        format: binary
```

Could you please clarify if comma-separated media types are actually supported by the Specification?

If yes, how does this work? Is it just a shorthand syntax in case multiple media types have the same schema? E.g. same as
```
  content:
    image/png:
      schema:
        type: string
        format: binary
    image/jpeg:
     schema:
        type: string
        format: binary
```
