### ISSUE TITLE
Callback clarifications

### ISSUE THREAD

**Issue by hkosova** [OAI/OpenAPI-Specification#1302]
1. Can the `callbacks` map contain multiple Callback Objects with the same runtime expression? Technically it would be valid YAML/JSON, but is it valid accoding to the OpenAPI Specification?

E.g., PubSubHubbub ([example](http://pubsubhubbub.superfeedr.com/)) may involve an extra verification step that is sent to the same callback URL. Can this scenario be defined like this
```
      callbacks:
        verification:
          '{$request.body#/hub.callback}':
            ...
        feedUpdate:
          '{$request.body#/hub.callback}':   # <-- same expression as the previous one
            ...
```
or does the Specification require a single path item for both callbacks in this scenario?
```
      callbacks:
        hubCallbacks:
          '{$request.body#/hub.callback}':
            get:
              # verification step
            post:
              # feed update
```
<br/>

2. 
> Callback Object
> A map of possible out-of band callbacks (_note: plural!_) related to the parent operation. Each value in the map is a Path Item Object that describes a set of requests that may be initiated by the API provider and the expected responses.

"map of ... callbacks" and "Each value in the map" read as if a single callback may include multiple path items like so --
```
      callbacks:
        alerts:
          '{$request.body#/error}':
            ...
          '{$request.body#/clear}':
            ...
        webhooks:
          '{$request.body#/webhookUrl}'
```

Is this the intended meaning?
