### ISSUE TITLE
Is there is a way to merge enums into one flat enum, or list?

### ISSUE THREAD

**Issue by amalahussein** [OAI/OpenAPI-Specification#1320]
I am using the 2.0 spec and I have a field which I am using in a model as well as a path param where the value can be from one of three different enums. Using the syntax below is turning into an array with 3 enums. However, I would like it to be one flat enum. Is there any way to achieve this? 

Thanks so much:

```
    properties:
      type:
        type: "string"
        enum: 
        - *unitTypes
        - *componentTypes
        - *snootTypes
```
