### ISSUE TITLE
Components fields name example too restrictive?

### ISSUE THREAD

**Issue by PerthCharern** [OAI/OpenAPI-Specification#1387]
Components fields name currently has this regex as restrictions: `^[a-zA-Z0-9\.\-_]+$` 
This was mainly discussed and agreed on in #634. 

I found this restriction a little too restrictive. I'd imagine that for the Schemas part of the component, most people will use class names as field names. Allowing the period (.) is good because that allows you to add namespace to class name `Namespace.ClassName`. 

However, quite a number of languages have generics and APIs can have request body that are of type implementing generics. The current allowed characters make it very difficult to represent class name that is derived from generic type. The most intuitive (I think) way to represent generic class name as string is to use some kind of brackets/parentheses `Namespace.GenericClassName(AnotherClassName)`. Of course, one can bypass this by using the allowed underscore or hyphen instead, but that just looks plain ugly.

Should we allow parentheses and/or brackets?

**Comment by MikeRalphson** [comment]
Only the top-level schema object name must conform to the components key regex.

Is it possible you could do something like

```yaml
components:
  schemas:
    container:
     type: object
     properties:
       namespace.generic(type):
         type: ...
```

or

```yaml
components:
  schemas:
    namespace:
     type: object
     properties:
       generic(type):
         type: ...
```

and use a `$ref` nested through the `container`/`namespace` object, e.g.:

```yaml
$ref: '/components/schemas/container/type(generic)'
