### ISSUE TITLE
Example of "All Schemes" Security Requirement

### ISSUE THREAD

**Issue by stevendearborn** [OAI/OpenAPI-Specification#1429]
Can anyone provide an OpenAPI 3.0 example of the following, from the specification:

"Security Requirement Objects that contain multiple schemes require that all schemes MUST be satisfied for a request to be authorized. This enables support for scenarios where multiple query parameters or HTTP headers are required to convey security information."

The two examples provided are API key and OAuth 2.0.

**Comment by hkosova** [comment]
```yaml
components:
  securitySchemes:
    apiKey1:
      type: apiKey
      in: header
      name: X-Foo
    apiKey2:
      type: apiKey
      in: header
      name: X-Bar

security:
  - apiKey1: []
    apiKey2: []
```
