### ISSUE TITLE
OpenAPI 3: add support for Token authentication

### ISSUE THREAD

**Issue by collimarco** [OAI/OpenAPI-Specification#1437]
I have [a Rails application](https://pushpad.xyz/docs/rest_api) that uses the following *standard* for authentication:

```
Authorization: Token token="ACCESS_TOKEN"
```

Currently this authentication method is not supported by the spec. 

However the OpenAPI should support this method because is [a standard](https://tools.ietf.org/html/draft-hammer-http-token-auth-01) and moreover it is widely used in production - see Rails'  [authenticate_or_request_with_http_token](http://api.rubyonrails.org/v4.2.10/classes/ActionController/HttpAuthentication/Token.html) for example.

**Comment by epastorino** [comment]
I have the same problem. I'm using django-rest-framework with token authentication.
OpenAPI should support this method, I agree.
Meanwhile, I'm documenting my APIs using this workaround, inspired by [this response from stackoverflow](https://stackoverflow.com/a/47679963):
```
components:
  securitySchemes:
    Token:
      type: apiKey
      in: header
      name: Authorization
      description: Enter your token in the format **Token &lt;token>**
```

**Comment by darrelmiller** [comment]
@collimarco @epastorino  OpenAPI v3 does support any security scheme that uses the Authorization header.

```
components:
  securitySchemes:
    Token:
      type: http
      scheme: Token
```
