### ISSUE TITLE
Require property based on another property value

### ISSUE THREAD

**Issue by tmdoit** [OAI/OpenAPI-Specification#1490]
I have the following scheme:
```yaml
    Issue:
      type: "object"
      properties:
        data:
          type: "object"
          properties:
            type:
              type: "string"
              example: "issue"
            attributes:
              type: "object"
              properties:
                altAddress:
                  type: "boolean"
                  example: false
                altAddressCustomerName:
                  type: "string"
                  minLength: 3
                  maxLength: 200     
                altAddressStreet:
                  type: "string"
                  minLength: 3
                  maxLength: 100       
                altAddressPostalCode:
                  type: "integer"
                  format: "int32"
                  minLength: 5
                  maxLength: 5
                altAddressCity:
                  type: "string"
                  minLength: 3
                  maxLength: 30     
```
I want to altAddress... properties to be required if altAddress property is set to true. How can I achieve this?
