### ISSUE TITLE
Is "examples" (plural) supported inside schemas in 3.0.x?

### ISSUE THREAD

**Issue by hkosova** [OAI/OpenAPI-Specification#1494]
OpenAPI Specification versions: 3.0.0, 3.0.1

The [Example Object Example](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#example-object-example) section demonstrates the usage of the `examples` (plural) keyword inside a schema:

```yaml
# in a model
schemas:
  properties:
    name:
      type: string
      examples:
        name:
          $ref: http://example.org/petapi-examples/openapi.json#/components/examples/name-example
```

However, the [Schema Object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#schemaObject) description only mentions the [`example`](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#fixed-fields-20) keyword (singular) but  not `examples` (plural).

Is `examples` actually supported inside schemas?
Or is the abovementioned example invalid?
