### ISSUE TITLE
Any of - while selecting the query parameters in Swagger using Open API 3.0.0

### ISSUE THREAD

**Issue by iappa1** [OAI/OpenAPI-Specification#1500]
Hi

I have an API , which can accept multiple parameters like,

https://abc.com/findStatus?petid=12334
https://abc.com/findStatus?petname=cuty
https://abc.com/findStatus?petowner=John

I get same response for all the above url's.

How Can I document this in Swagger using OenAPI 3.0.0 ?

Thanks.

**Comment by hkosova** [comment]
Are these parameters optional? Or does the endpoint require at least 1 (any) parameter?

Are these parameters mutually exclusive? Or can they be used together, e.g. https://abc.com/findStatus?petname=cuty&petowner=John?

**Comment by iappa1** [comment]
The endpoint requires at least  any one of those parameters, but should be documented as a single API.

They cannot be used together.

**Comment by hkosova** [comment]
So you have mutually exclusive parameters. A possible way is to define them as a single object-type parameter with additional constraints so that only property can be present, and use `style: deepObject` to serialize this object as `?propName=value`.

```yaml
      parameters:
        - in: query
          name: filter
          required: true
          schema:
            type: object
            properties:
              petid:
                type: integer
                example: 12334
              petname:
                type: string
                example: cuty
              petowner:
                type: string
                example: John
            minProperties: 1
            maxProperties: 1
            additionalProperties: false
          style: deepObject
          explode: true
```
or maybe
```yaml
      parameters:
        - in: query
          name: filter
          required: true
          schema:
            type: object
            properties:
              petid:
                type: integer
                example: 12334
              petname:
                type: string
                example: cuty
              petowner:
                type: string
                example: John
            additionalProperties: false
            oneOf:
              - required: [petid]
              - required: [petname]
              - required: [petowner]
          style: deepObject
          explode: true
```

There's also a proposal to [allow query strings in paths](https://github.com/OAI/OpenAPI-Specification/issues/164), which (if implemented) would make your scenario a bit easier to describe.
