### ISSUE TITLE
Are indexes in the query parameter array representable?

### ISSUE THREAD

**Issue by jcarres-mdsol** [OAI/OpenAPI-Specification#1501]
I understand how to represent in 2.0 and 3.0 these query parameters with OpenAPI:
```
?list=x&list=y
```

But I can't understand if it is possible or not (so I imagine, not?) to represent this:
```
?list[0]=x&list[1]=y
```
or this:
```
?obj[x][0]=a&obj[x][1]=b
```

We use indexes so we can mix arrays and maps with the same notation, i.e. we would also have:
```
?map[x]=1&map[y]=2
```

Is this even representable today? Any hack around it if not?

**Comment by jcarres-mdsol** [comment]
@webron, I think you originally added collectionFormat and style so probably you have given this some thought

**Comment by hkosova** [comment]
Your last example `?map[x]=1&map[y]=2` can be defined an an object parameter with `style: deepObject`:
```yaml
      parameters:
        - in: query
          name: map
          schema:
            type: object
            properties:
              x:
                type: integer
              y:
                type: integer
          style: deepObject
          explode: true
```
or
```yaml
      parameters:
        - in: query
          name: map
          schema:
            type: object
            additionalProperties:
              type: integer
          style: deepObject
          explode: true
```

Not sure about other examples though.
