### ISSUE TITLE
Introduce tags hierarchy

### ISSUE THREAD

**Issue by dtsaryov** [OAI/OpenAPI-Specification#1507]
Hello.

My proposal is to add an ability to create tags hierarchy, for example:

```yaml
tags:
  - name: Entites
    description: CRUD entities operations
      - User
      - Group
  - name: Services
    description: Predefined queries execution
      - FooService:
        - name: ...
          description: ...
      - BarService:
        - name: ...
          description:
```

It'll help to group operations in case of generic REST API.
