### ISSUE TITLE
Configuring global request parameters

### ISSUE THREAD

**Issue by hjpbarcelos** [OAI/OpenAPI-Specification#152]
Could we have a way for declaring global request parameters?

I'm working on an aggregation API that has its own authentication method. What I do is just to forward an `Authentication` header to these APIs that will handle the authentication.

Currently, I have to set:

``` yaml
    parameters:
        - name: authorization
        in: header
        description: The user access token
        required: true
```

in every request.

Is there an easy way to include a option that allows us to configure global request parameters? I'm pretty sure I'm not the only one with this need. Some coleagues of mine have worked with swagger some time ago and they told me they had faced the same issue.

Suggestions I have for this:
1. Having an wildcard entry on paths:
   
   ``` yaml
   *:
       post:
           parameters:
               - name: authorization
                 in: header
                 description: The user access token
                 required: true
       get:  
           parameters:
               - name: authorization
                 in: header
                 description: The user access token
                 required: true
   ```
   
   It could be very repetitive if we needed to set the parameters for every request method.
2. Having an wildcard entry on paths that allows global path and global method configuration:
   
   ``` yaml
   *:
       *:
           parameters:
               - name: authorization
                 in: header
                 description: The user access token
                 required: true
       post:
           parameters:
               - name: another_one
                 in: body
                 description: Something
                 required: true
   ```
   
   This way, we could set global parameters for every method and refining if needed.

There should also be a way to ignore these global configurations, such as:

``` yaml
/signin:
    post:
        parameters:
            - name: username
            # ...
        use_global_parameters: false
```

Also, there should be possible to overwrite the global configurations, like:

``` yaml
*:
    *:
        parameters:
            - name: something
                in: query
                description: something
                required: true
    post:
        parameters:
            - name: something
                in: body
                description: Something
                required: true
```

**Comment by shatestest** [comment]
@webron  can you please help me how to access apiKey at url after setting it.  https://stackoverflow.com/questions/49050969/setting-swagger-apikey-in-version-3-0

**Comment by deepan-itela** [comment]
Is it possible to set a default apikey value like the one below.

```
securityDefinitions:
  forwarded:
    name: authorization
    type: apiKey
    in: header
```

I tried this, but it doesn't work.
