### ISSUE TITLE
Ambiguous parameter decoding?

### ISSUE THREAD

**Issue by jwalton** [OAI/OpenAPI-Specification#1535]
This is more a question, just to make sure I'm not missing something;

Suppose I have:

```yaml
paths:
  '/api/{var}':
    get:
      parameters:
        name: var
        in: path
        required: true
        style: simple
        exploded: false
        schema:
          oneOf:
            - type: array
              items:
                type: string
            - type: object
              properties:
                a:
                  type: string
```

Then if I get a request to `/api/a,b`, there's no way for me to know if `var` should be `{"a": "b"}`, or if `var` should be `["a", "b"]`, right?
