### ISSUE TITLE
This is not an issue just an request/query

### ISSUE THREAD

**Issue by bhagatdinesh** [OAI/OpenAPI-Specification#1549]
Referring file: [petstore-expanded.yaml](https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v3.0/petstore-expanded.yaml)
It is possible to deprecated entire API object, API parameters or Schema object but is it possible to mark an field as deprecated?
e.g.
```
   ...
components:
    schemas:
        NewPet:
            required:
            - name
            properties:
            name:
            type: string
            deprecated: true
            tag:
            type: string
  ...
```
