### ISSUE TITLE
Add values to an existing enum in an array

### ISSUE THREAD

**Issue by Pauline86** [OAI/OpenAPI-Specification#1550]
Hello,

I'm new at OpenAPI.
I have an object with 2 versions, and a base enum containing Cat, Dog and Rabbit.
base.yaml:
```
pet:
  type: string
  enum:
    - Cat
    - Dog
    - Rabbit
```
In v1(v1.yaml) object, I import the base enum in an array as following:
```
pets:
          xml:
            name: pets
            wrapped: true
          properties:
            pet:
              allOf:
                - $ref: './base.yaml#/components/schemas/pet'
```

In v2 object (v2.yaml file), I want to add some values to the base enum : Horse and Parrot. I'm doing as following:
```
pets:
   xml:
     name: pets
     wrapped: true
        properties:
          pet:
            allOf:
              - $ref: './v1.yaml#/components/schemas/pets/properties/pet'
              - $ref: './v2.yaml#/components/schemas/pet'
pet:
  type: string
  enum:
    - Horse
    - Parrot
```

I encounter a problem: alone, v1 works fine. When I add the v2 object to be able to switch version, the pet list of version 1 takes the values of version 2.

How can I have v1 values for v1 object and v2 values for v2 object instead of having v2 values for v1 and v2 objects?

Thank you by advance
