### ISSUE TITLE
Hypermedia and path variable

### ISSUE THREAD

**Issue by boubasse** [OAI/OpenAPI-Specification#1553]
Hi everyone,

I'm facing an issue an i don't know if there is a solution yet.

Is it possible to pass an absolute URI from a links object as a variable for a path ?

Example :

```yaml
links:
  pathLink:
    operationId: whatever
      parameters:
        pathUri: '$response.body#_links/whatever/href'
```
And then having as a path :

```yaml
paths:
  '{pathUri}':
    get:
    operationId: whatever
      parameters:
        - name: pathUri
          in: path
          required: true
          schema:
            type: string
```

According to the specification, paths must be relative but in that specific case could it be acceptable ?

Thanks for your answers.

**Comment by darrelmiller** [comment]
@boubasse  No it is currently not possible and it is something we would really like to fix.  I have debated doing something like you suggest but the problem is that `paths` only contain the path part of the URI.  Some feedback we have received is that people want to be able to specify the complete URL in the input URL.  This can get messy if the path matches with an existing path, but the host or query parameters don't.

Having said this, if we are able to support multi-segment path parameters #1459  then it would become possible to describe a path as you suggest.

**Comment by boubasse** [comment]
@darrelmiller It means that currently the power of hypermedias cannot be specified.
Since hypermedias usually contain absolute URI, it means that at the moment, we cannot use absolute URI for paths according to your post.
But let's suppose that we are using a relative URI (e.g. '/users/1') in the hypermedia.
Since the OAS syntax involves using a "/" to specify a path item, the result would be '//users/1'.

At least, I think it should be interesting to consider removing the slash from path.

Using relative URI in hypermedias would theoritically respect the OAS, wouldn't it ?

**Comment by handrews** [comment]
> At least, I think it should be interesting to consider removing the slash from path.
>
> Using relative URI in hypermedias would theoritically respect the OAS, wouldn't it ?

I confess I've always found the choice of path concatenation over RFC 3986 reference resolution confusing.  Reference resolution has its own slightly counter-intuitive aspects, but it is how literally ever other hypermedia format works that I'm aware of.

**Comment by darrelmiller** [comment]
@handrews That leading slash in paths makes me sad every time I see it.  

@boubasse I don't think removing the slash is feasible in a non-breaking way.  So, I think we are stuck with it until at least 4.0

However, there is another more radical thing that might be doable in a point release.  We possibly could introduce a new top level concept called 'resources'.  The `resources` node would use a complete URI Template to identify the resource.  This would enable describing resources that can only be discovered via links and also enable supporting operations that are differentiated by query parameter.

```
resources:
  '{uriTemplate}':
    get:
    operationId: whatever
      parameters:
        - name: pathUri
          in: path
          required: true
          schema:
            type: string
```

This would be a big change and I don't know what the appetite for this kind of change is in the community.
