### ISSUE TITLE
enum holding object literals as values?

### ISSUE THREAD

**Issue by pwrinc** [OAI/OpenAPI-Specification#1602]
Hi,

Regarding Open Api 3.0.0:

is it possible to assign enum to a property of type `object`? What I need is something like the below having in mind that only values `{"name":"admin", "value":1}` and `{"name":"user", "value":2}` are valid values for property `userRoles`
```
userRoles:
  type: object
  properties:
    name: 
      type: string
    value:
      type: number
      format: integer
  enum:
  - name: "admin"
    value: 1
  - name: "user"
    value: 2
```
