### ISSUE TITLE
Proposal: Parameters in cookie

### ISSUE THREAD

**Issue by BigstickCarpet** [OAI/OpenAPI-Specification#161]
Currently, the only way we can define a cookie parameter is like this:
````yaml
parameters:
  - name: Cookie
    in: header
    type: string
    required: true
````
But that just requires a cookie - any cookie - to be present.   There's no way to distinguish between third-party cookies (e.g. google analytics, advertising, etc.) and our API's cookies.   It would be nice to be able to do this:
````yaml
parameters:
  - name: myApiCookie
    in: cookie
    type: string
    required: true
````
