### ISSUE TITLE
schema property required field

### ISSUE THREAD

**Issue by GeorgeR** [OAI/OpenAPI-Specification#1612]
It would be good if you could say if a property is required or not.

**Comment by MikeRalphson** [comment]
Hi, this is the job of the `required` property:

```yaml
components:
  schemas:
    MySchema:
      type: object
      properties:
        a:
          type: string
        b:
          type: integer
      required:
      - a
```

Note that `required` is a sibling of the `properties` object, and does not live within it.

[Here](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#schema-object) are the properties which are taken unchanged from JSON-Schema Draft 5 and which ones have subtly different meanings. The OAS really should be read in conjunction with the [JSON Schema](http://json-schema.org/specification-links.html#draft-5) spec.
