### ISSUE TITLE
property type date

### ISSUE THREAD

**Issue by GeorgeR** [OAI/OpenAPI-Specification#1613]
Could we get a type of date? Requiring a string to be formatted in a certain way.

**Comment by MikeRalphson** [comment]
This is the job of the `format` property, which works alongside the `type` property (which represents the base JSON/JSON-Schema types only).

```yaml
parameters:
- name: date
  in: query
  schema:
    type: string
    format: date
```

See the list [here](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#data-types), but you can also define your own `format` values.
