### ISSUE TITLE
property type enum

### ISSUE THREAD

**Issue by GeorgeR** [OAI/OpenAPI-Specification#1614]
Where the enum is described as an array of possible strings

**Comment by MikeRalphson** [comment]
`enum` is a property of the `schema` object (as well as the `server variable` object), as opposed to a `type`.

You can do the following:

```yaml
components:
  schemas:
    MySchema:
      type: string
      enum:
      - value1
      - value2
```

One benefit of this is that the `enum` array can contain values of any `type`, such as `integer` etc.
