### ISSUE TITLE
Support for Constant Value in API

### ISSUE THREAD

**Issue by duckladydinh** [OAI/OpenAPI-Specification#1620]
Since OpenAPI can be used to generate client code, it is good to support some constant value in the API itself.

Use case: When you add type info to a class as a properties, we need that property for deserialization and the value of this property will never change.

**Comment by MikeRalphson** [comment]
Can you not do this with an `enum` property which only has one value?

```yaml
MySchema:
  type: object
  properties:
    MyProperty:
      type: string
      enum:
      - constantValue
```
