### ISSUE TITLE
[Question] How do I define a constructor?

### ISSUE THREAD

**Issue by yeikel** [OAI/OpenAPI-Specification#1634]
Using the [petstore-simple.json](https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v2.0/json/petstore-simple.json) as a starting point .

How can I define a mandatory constructor?

For example , for the Pet definition  : 

```
   pet:
    type: object
    required:
      - id
      - name
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      tag:
        type: string
```
