### ISSUE TITLE
How to differentiate strings from numbers in parameters

### ISSUE THREAD

**Issue by DmitriiTrofimov** [OAI/OpenAPI-Specification#1649]
How to differentiate strings from numbers in parameters, if payload is always string?
Example:
```
parameters:
  - name: sample
    in: query
    schema:
      oneOf:
        - type: string
        - type: integer
```

Is valid schema for next payload `.../?sample=5`? In this payload `5` is string.
