### ISSUE TITLE
Code generation hints

### ISSUE THREAD

**Issue by silkentrance** [OAI/OpenAPI-Specification#1650]
As of now, we only have the ``xml`` property for adding hints to the model for extended XML support.

I would also like to introduce ``abstract`` and ``virtual`` to the mix.

With ``abstract`` meaning that a given entity is to be rendered out as an abstract class and ``virtual`` meaning that the entity is not rendered out at all.

Use cases would be ``allOf`` and ``anyOf``, where we could declared reusable entities in the specification that would find no correspondence in the generated code when marked as ``virtual``.

When marked as ``abstract`` however, there would be abstract classes in the code that could also be used as base classes in languages where we have only single inheritance, at least in Swagger 2.0.

Abstract:

```
components:
  AbstractPet:
    type: object
    abstract: true
  Dog:
    allOf:
      - AbstractPet
      - type: object
        ...
```

would be rendered as 

```
abstract class AbstractPet {}

class Dog extends AbstractPet {}
```

Abstract and Virtual in combination:

```
components:
  AbstractPet:
    type: object
    abstract: true
  VirtualCanBark:
    type: object
    virtual: true
    properties:
      barkSound:
        type: string
  Dog:
    allOf:
      - AbstractPet
      - VirtualCanBark
      - type: object
        ...
```

would again be rendered as 

```
abstract class AbstractPet {}

class Dog extends AbstractPet {}
```

where the properties from VirtualCanBark will be mixed into Dog as is currently the case.

The only difference being that we would no longer have generated code for these virtuals as separate classes and that we still have a working inheritance chain between dog and pet.

The exact handling of the virtuals however, is definitely a responsibility of the respective code generators and the target languages and frameworks thereof and the idioms such languages and frameworks support.
