### ISSUE TITLE
Get rid of $ref

### ISSUE THREAD

**Issue by silkentrance** [OAI/OpenAPI-Specification#1651]
$ref gives me headaches :grin:.

Why not just use ``type`` for this?
Where type can be either a simple string, e.g. ``object`` or ``string`` or a path that is either relative (to the current specification) or pointing to some other specification either using a relative path ``../...`` or an absolute path ``/...`` or even an URL.

Example:

```
components:
  Foo:
    allOf:
      - type: ./components/Bar
      - type: object
         properties:
            foobar:
               type: ./components/UUID
  Bar:
    allOf:
      - type: ../other-schemas/schema-one/components/SomeDeclaration
      - type: object
        properties:
           ...
  UUID:
    type: string
    format: uuid
```

or even with ``schema``

```
parameters:
   foo:
     in: body
     schema:
       type: ./components/Foo
```

That way we would have less special casing, i.e. ``$ref`` vs ``type`` and the specification would look more uniform. 

~~(Which is something that could well be addressed over at JSON Schema, too)~~
