### ISSUE TITLE
Doc improvements: query formats (n/a usage, "rendering")

### ISSUE THREAD

**Issue by KES777** [OAI/OpenAPI-Specification#1663]
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#parameter-object-examples

Would it be more clear if an example of query url provided?

For an example, how url query should looks for this? How to repeat the parameter?

>An optional query parameter of a string value, allowing multiple values by repeating the query parameter:

**Comment by silkentrance** [comment]
@KES777 well, this depends on the target language and framework for which you generate the code from the OAS specification. Or do you want to do that manually?

**Comment by KES777** [comment]
I understand that as next:

1. the query come to server: `?color=blue&color=black&color=brown`
2. The validator checks that `color` is array and its values are `strings`:
```
name: id
in: query
description: ID of the object to fetch
required: false
schema:
  type: array
  items:
    type: string
style: form
explode: true
```

Also I do not understand why it is called `rendering` if this is? parsing query:

>The following table shows examples of **rendering** differences for each value.
