### ISSUE TITLE
Add example/s as "Operation Request" child

### ISSUE THREAD

**Issue by chatelao** [OAI/OpenAPI-Specification#1673]
To define valid parameter **combination** examples, it would be nice to define consistent examples for an operation and not only on JSON / single-parameter base.

The alternative to use the same Id on every example is less intuitive, especially when reusing type definitions of parameters

**Comment by MikeRalphson** [comment]
Could you show an example of what you'd like to be able to do to clarify your question?

**Comment by hkosova** [comment]
I think the OP is asking for the ability to provide **examples for different _combinations_ of parameters**.

Consider an item search operation that supports pagination and sorting:
```yaml
paths:
  /items:
    get:
      parameters:
        - in: query
          name: offset
          schema:
            type: integer
            default: 0
            minimum: 0
        - in: query
          name: limit
          schema:
            type: integer
            minimum: 0
            maximum: 50
            default: 20
        - in: query
          name: sort
          schema:
            type: string
            enum: [asc, desc]
            default: asc
        - in: query
          name: sort_by
          schema:
            type: string
            enum: [name, created]
            default: name
```

As a technical writer, I would like to provide examples for:
* get the first 50 items: `?limit=50`
* get items 5-10: `?offset=4&limit=5`
* get the last created item: `?sort=desc&sort_by=created&limit=1`

As a user of an interactive API console, I would like to use these examples to fill in the corresponding values for multiple parameters at once.

<br/>

The current workaround is to add such examples to the operation `description`.
