### ISSUE TITLE
URL-encoding for operationRef

### ISSUE THREAD

**Issue by Alan-Cha** [OAI/OpenAPI-Specification#1677]
I was under the impression that *operationRef* does not need URL-encoding. 

For example, in the following snippit taken directly from the [link object documentation](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#link-object)...

```
links:
  UserRepositories:
    # returns array of '#/components/schemas/repository'
    operationRef: '#/paths/~12.0~1repositories~1{username}/get'
    parameters:
      username: $response.body#/username
```

... `{` and `}` are not encoded, i.e. replaced with `%7B` and `%7D`, like in the following:

```
links:
  UserRepositories:
    # returns array of '#/components/schemas/repository'
    operationRef: '#/paths/~12.0~1repositories~1%7Busername%7D/get'
    parameters:
      username: $response.body#/username
```

***

However, after talking to a developer of an OAS validator, I am doubtful... I was told that because *operationRef* is defined as a **reference** in the OAS, it needs URL-encoding.  

Here is the [link](https://github.com/Mermade/oas-kit/issues/85) to the discussion. The last two exchanges are most important to this topic. 

Could you clarify if *operationRef* needs URL-encoding?
