### ISSUE TITLE
what method to use when link objects use operationRef

### ISSUE THREAD

**Issue by dret** [OAI/OpenAPI-Specification#1688]
i may just not be able to find it, but it seems to me that when link objects use `operationRef` (instead of `operationId`), it is not specified which method to use for the request? i am looking at the examples ar https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#operationref-examples and wonder how an actual request would look like. i don't know how to figure out which method to use.

**Comment by MikeRalphson** [comment]
The `operationRef` is a reference into an OAS document which points at an `operation` object. The key of that object (the last component of the `operationRef`) is the HTTP method to use.

```yaml
links:
  UserRepositories:
    # returns array of '#/components/schemas/repository'
    operationRef: '#/paths/~12.0~1repositories~1{username}/get'
    parameters:
      username: $response.body#/username
```

here the method is `get`.
