### ISSUE TITLE
Question about server URL specification

### ISSUE THREAD

**Issue by c00kie-m0nsta** [OAI/OpenAPI-Specification#1717]
For example, I have defined the following `servers` OpenAPI object in YAML: 
```
servers:
- url: https://{hostname}/api/model/
  variables:
    hostname:
      default: localhost
```
this OpenAPI spec will be rendered on different servers, so there is a need to have `{hostname}` dynamically resolve at the time the spec is being rendered. 

Is there a way this can be achieve? One way is to manually modify the `servers` object before rendering it.
