### ISSUE TITLE
Yet another Overlay proposal

### ISSUE THREAD

**Issue by darrelmiller** [OAI/OpenAPI-Specification#1722]
A continuation of the conversation in #1442 but with a new approach.

----

# OpenAPI Overlays

In recent months we have been discussing various use cases for overlays and various solutions.  The following proposal takes a somewhat more radical approach to the problem.  It is a more ambitious proposal than the others we have seen before but the additional complexity does allow for supporting many of the scenarios that have been discussed to date.

#### <a name="overlayDocument"></a>Overlay Document

An overlay document contains a list of [Update Objects](#overlayUpdates) that are to be applied to the target document.  Each [Update Object](#updateObject) has a `target` property and a `value` property.  The `target` property is a JSONPath query that identifies what part of the target document is to be updated and the `value` property contains an object with the properties to be overlayed.

----
Note: 
I have previously argued against using JSONPath due to its lack of formal specification and due to the fact that we already use JSON Pointers in OAS documents, there is risk of confusion.  However, based on further research there do appear to be significant body of implementations and the defacto Javascript implementation uses a BNF Grammar to define the syntax.  This grammar could be used to create a normative description of the JSONPath syntax.   

----

#### <a name="overlayObject"></a>Overlay Object

This is the root object of the [OpenAPI Overlay document](#oasDocument).

##### Fixed Fields

Field Name | Type | Description
---|:---:|---
<a name="overlayDescription"></a>description | `string` | A human readable description of the purpose of the overlay.
<a name="overlayUpdates"></a>updates | [[Update Object](#updateObject)] | A list of update objects to be applied to the target document.

The list of update objects MUST be applied in sequential order to ensure a consistent outcome.  This enables objects to be deleted in one update and then re-created in a subsequent update.

#### <a name="updateObject"></a>Update Object

This object represents one or more changes to be applied to the target document at the location defined by the target JSONPath.

##### Fixed Fields

Field Name | Type | Description
---|:---:|---
<a name="updateTarget"></a>target | `string` | A JSONPath expression referencing the target objects in the target document.
<a name="updateValue"></a>value | [Any](#valueObject) | An object with the properties and values to be updated in the target document.

The properties of the `Value Object` MUST be compatible with the target object referenced by the JSONPath key.  When the Overlay document is applied, the properties in the `Value Object` replace properties in the target object with the same name and new properties are appended to the target object.

##### Structured Overlays Example

When updating properties throughout the target document it may be more efficient to create a single `Update Object` that mirrors the structure of the target document. e.g.

```yaml
overlay:
  description: Structured Overlay
  updates:
    - target: "$"
      value:
        info:
            x-overlay-applied: structured-overlay
        paths:
            "/":
                summary: "The root resource"
                get:
                    summary: "Retrieve the root resource"
                    x-rate-limit: 100
            "/pets":
                get:
                    summary: "Retrieve a list of pets"
                    x-rate-limit: 100
        components:
        tags:
```

##### Targeted Overlays

Alternatively, where only a small number of updates need to be applied to a large document, each [Update Object](#updateObject) can be more targeted.

```yaml
overlay:
  description: Structured Overlay
  updates:
    - target: $.paths['/foo'].get
      value:
        description: This is the new description
    - target: $.paths['/bar'].get
      value:
        description: This is the updated description
    - target: $.paths['/bar']
      value:
        post:
          description: This is an updated description of a child object
          x-safe: false
```

##### Wildcard Overlays Examples

One significant advantage of using the JSONPath syntax that it allows referencing multiple nodes in the target document.  This would allow a single update object to be applied to multiple target objects using wildcards.

```yaml
overlay:
  description: Update many objects at once
  updates:
    - target: $.paths[*].get
      value:
        x-safe: true
    - target: $.paths[*].get.parameters[name eq 'filter' && in eq 'query']
      value:
        schema:
          $ref: "/components/schemas/filterSchema"
```

##### Array Modification Examples

Due to the fact that we can now reference specific elements of the parameter array, it does open the possibilty to being able to add parameters and potentially remove them using a `null` value.

```yaml
overlay:
  description: Add an array element
  updates:
    - target: $.paths[*].get.parameters[(@.length)]
      value: 
        name: newParam
        in: query
```

```yaml
overlay:
  description: Remove a array element
  updates:
    - target: $.paths[*].get.parameters[name eq 'dummy']
      value: null
```

### Benefits

- This approach addresses the two distinct approaches of structured overlay vs targeted overlay which suits distinct but equally valid scenarios.
- Addresses the problem of modifying the parameters array and removes the need to replace the entire array when a small change is required.
- Allows sets of related overlays to be stored in a same file.
- Enables updating a set of objects based on a pattern. This might be an effective way of apply common behaviour across many operations in an API.

### Challenges
- Tooling will need a JSONPath implementation.
- Large overlays may be slow to process.
- Multiple complex pattern based overlays may cause overlapping updates causing confusing outcomes.

**Comment by darrelmiller** [comment]
Should this be a distinct spec from OpenAPI?

**Comment by darrelmiller** [comment]
Should the core document reference the overlay or should the overlay reference the core document?  Or should the relationship be dynamic and external to the spec?

Should overlays be composable?  Can I reference one overlay from another?

**Comment by darrelmiller** [comment]
Consensus:  
- Core document should not reference the overlay?
- Separate the Overlay spec from OAS.  (Don't know if it should have a dependency on OAS?)
- No strong objection to JSONPath, but needs to have an actual written spec.
- No objections to extra complexity of structural and targeted overlays

**Comment by darrelmiller** [comment]
Suggestion for 3.1 that extensions that have a null value have the same meaning as the extension not being present.

**Comment by MikeRalphson** [comment]
See also http://jmespath.org

**Comment by MikeRalphson** [comment]
That said, if we prefer to align things a little more to the OAS, then I'd be tempted to slightly rework the structure as follows:

```yaml
overlay: 1.0.0
info:
  version: 1.0.0
  title: My Nice Overlay
base: ./openapi.yaml # an optional uri_reference to the base openapi document OR another overlay document
updates:
- target: info
  value:
    description: Overlay applied
```
