### ISSUE TITLE
What is meaning of maxLength or minimum

### ISSUE THREAD

**Issue by vinh25101995** [OAI/OpenAPI-Specification#1754]
I'm learning about swagger.I creat a specification file, in this file, i have code like this

```yaml
paths:
  /rcp1:
   get:
     summary: UCS
     description: test swagger
     parameters: 
      - in: query
        name: ATSUKAISHA_CODE
        schema:
          type: string
          maxLength: 5
        required: true 
        description: ATSUKAISHA_CODE
```

Detail: [https://app.swaggerhub.com/apis/Vinh2510/TestAPI2/0.0.1](url)

So we have information like maxLength in this code, but when render nothing is created. So what is the meaning of this information.
Thank you for help!
