### ISSUE TITLE
externalDocs URL field needs a label

### ISSUE THREAD

**Issue by stueynz** [OAI/OpenAPI-Specification#1760]
Here's my tags object in a non-trivial OpenAPI spec I'm writing:

```
tags: 
  - name: Providers
    description: "Everything about Providers & other Organisations"
    externalDocs:
      description: "Provider & Staff Domain in SIF NZ data model"
      url: http://localhost:8080/DomainMap.html#Domain__Provider
```
That URL turns up in Swagger-UI  - but man it's ugly.
What I'd like to have is something like this:
```
tags: 
  - name: Providers
    description: "Everything about Providers & other Organisations"
    externalDocs:
      description: "Provider & Staff Domain in SIF NZ data model"
      link: 
        url: http://localhost:8080/DomainMap.html#Domain__Provider
        label: SIF NZ Provider Domain
```
That way we get to render a proper ``<a href="localhost:8080/DomainMap.html#Domain_Provider">SIF NZ Provider Domain</a>`` link in Swagger UI etc.

PS: some of my deep links to external docs have non-english characters in them, so the URLs get even uglier: ``http://localhost:8080/DomainMap.html#Domain__StudentWh%C4%81nau``
