### ISSUE TITLE
Can $ref be used to reference a single property within an object?

### ISSUE THREAD

**Issue by mindstretch23** [OAI/OpenAPI-Specification#1767]
Does the JSON/OAI spec support using $ref to reference an individual property within an object located in components/schemas section?

I'm trying to use this reference:

`$ref: '#/components/schemas/Weights/shippingWeight'`

...to only reference the `shippingWeight` property of the `Weights` object

Here's what I have in the components/schemas section:

```
components:
  schemas:
    Weights:
      type: object
      properties:
        shippingWeight:
          type: integer
          format: int32
```

Is this supposed to work per OAI spec? (seems reasonable).  I currently get a "could not resolve" path error in Swagger editor.
