### ISSUE TITLE
'parameter.description' vs. 'parameter.schema.description'

### ISSUE THREAD

**Issue by stephenfin** [OAI/OpenAPI-Specification#1788]
I had defined a parameter with its description in the `schema` field, like so:

```
parameters:
  Page:
    in: query
    name: page
    schema:
      description: A page number within the paginated result set.
      title: Page
      type: integer
```

This seems to be valid for the Schema Object [[1](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#schemaObject)]. However, I note that the Parameter object itself also has a `description` field [[2](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#parameterObject)].

```
parameters:
  Page:
    in: query
    name: page
    description: A page number within the paginated result set.
    schema:
      title: Page
      type: integer
```

Is this duplication and, if so, what is intended to take priority?
