### ISSUE TITLE
The Parameter object needs an "examples" property

### ISSUE THREAD

**Issue by ccleve** [OAI/OpenAPI-Specification#179]
The Response object has a nice {"example": ExampleObject} property which makes it easy to document an operation's response. The Parameter object needs the same thing, particularly when the parameter type is "body". What kind of body is the operation expecting?

**Comment by Kegsay** [comment]
+1 for automatic generation of curl examples.

**Comment by jasonh-n-austin** [comment]
Link to parent #565

**Comment by leandroferreira** [comment]
+1

**Comment by oliver-xapix-io** [comment]
+1

**Comment by etki** [comment]
+1

**Comment by ePaul** [comment]
Please note that you don't need to add a nwq comment for a "+1" anymore – there is the reaction button (on the top left of each comment) which allow you to "vote" on a comment. (@etki)

Only add a comment if it actually adds something.

**Comment by JD557** [comment]
I believe that this is now fixed (see https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.md#examples-object)

**Comment by tadhgpearson** [comment]
@JD557  - I don't believe so. 

I would have expected to see this example field in the[ schema object](https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.md#schemaObject) or the [parameter object](https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.md#parameter-object). The 'fixed fields' part of the schema object seems to suggest that this might be the case, but I only see examples provided for the requestBody, not for input parameters. 

So it's unclear to me if this is covered by the specification, and if so, what it might look like in real life.

**Comment by darrelmiller** [comment]
@tadhgpearson The Schema Object now has both `example` and `examples` in the fixed fields definition https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.md#fixed-fields-17

So, I would say currently, if schema supports it and parameters support schema then transitively parameters support examples.  Having said that, there is still work that needs doing on parameter, so this may change.

**Comment by tadhgpearson** [comment]
Yep... so it looks something like this?

```
        - name: origin
          in: query
          description: The [IATA code](https://en.wikipedia.org/wiki/International_Air_Transport_Association_airport_code) of the city from which the traveler will depart. See the location and airport interfaces for more information.
          required: true
          schema:
              type: string
              pattern: "^[A-Z]{3}$"
              example  NYC
```
