### ISSUE TITLE
Is it possible to convert object properties in response to enum type in query?

### ISSUE THREAD

**Issue by deser** [OAI/OpenAPI-Specification#1790]
For example, I have schema
```
type: object
      required: 
        - id
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        descrpition:
          type: string
        updatedAt:
          type: string
```

now I want to add query parameter which would filter which properties to return

```
...
            select:
                type: array
                items:
                  type: string
                  enum:
                      - id
                      - name
                      - description
                      - updatedAt

```

I want to do re-use properties of first schema object in enum of second's
