### ISSUE TITLE
Get OAuth token by providing client credentials

### ISSUE THREAD

**Issue by shwetashukla** [OAI/OpenAPI-Specification#1828]
Hi
I am facing an issue configuring oAuth for my contract . I have client_id , client_secret and token url to obtain the OAuth token , This oAuth token along with an api key is used to hit the API . I configured it like

```yaml
  OAuth2:
    type: oauth2
    flow: application
    tokenUrl: https://testOrg/testAAD/oauth2/token
    scopes:
      read: Grants read access
```

When I click "Authorize" button client_id and client_secret is visible and input it , I am not able to understand that the token obtained would be appended to header of the API request.

I am using swagger 2.0

Thanks
Shweta
