### ISSUE TITLE
Are there any working documentation generators for swagger 2.0?

### ISSUE THREAD

**Issue by chmac** [OAI/OpenAPI-Specification#183]
I have a schema that's something like (yaml):

```
/paths:
  /foo:
    post:
      summary: Post a Foo
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: Foo
definitions:
  Foo:
    properties:
      bars:
        type: array
        items:
          $ref: Bar
      baz:
        type: object
        schema:
          $ref: Baz
  Bar
    properties:
      name:
        type: string
        description: The name of Bar
  Baz
    properties:
      name:
        type: string
        description: The name of Ba
```

Is there any kind of generator out there that will make documentation from this? swagger-ui won't do anything at all, and swagger-editor won't render the Bar or Baz subtypes...
