### ISSUE TITLE
Cannot explode array correctly

### ISSUE THREAD

**Issue by LucaPrete** [OAI/OpenAPI-Specification#1839]
Guys, I'm using openapi 3.0.1.

I'm becoming crazy because I'm not able to explode an array (passed as query param) as I wish.
In principle, what would work for me would be the default (as far as I can tell from this page: https://swagger.io/docs/specification/serialization/).

What I'd like is to pass a list of status in the query this way
```
my_domain.com?status[]=accepted&status[]=canceled&status[]=open.
```

What I get instead -even forcing manually `style: form` and `explode: true`- is 
```
my_domain.com?status[]=accepted,canceled,open.
```

This array is just one of the query params I have to pass. The wired thing is that if I try to put explode to false all the names and values of the query string get flattened and get all separated by commas.
For example, assuming I have `status = [accepted,canceled,open]` and `name = try` as parameters to pass, I would get 
```
my_domain.com?status,accepted,canceled,open,name,try
```
which is even more wired...

I really don't understand what I'm doing wrong.

Here is the specific definition part:
```
TravelerOfferQueryParameters:
      in: query
      name: Traveler Offers get query parameters
      required: false
      explode: true
      style: form
      schema:
        type: object
        properties:
          'status[]':
            type: array
            items:
              type: string
              enum: ['accepted', 'cancelled', 'pending', 'expired']
          'name':
            type: string
            enum: ['try1', 'try2']
```

I'm either doing something obiously wrong, or I haven't understand something quite basic here :)

Any suggestion would be much appreciated.

Thanks!

**Comment by vvanpo** [comment]
You are embedding an array inside an object. Form-style query parameters don't mention being able to support that.

If instead you define separate parameters for `status[]` and `name`, you may achieve what you want:

```yaml
parameters:
- name: status[]
  in: query
  schema:
    type: array
    items:
      type: string
      enum:
      - accepted
      - cancelled
      - pending
      - expired
- name: name
  in: query
  schema:
    type: string
    enum:
    - try1
    - try2
```

I haven't tested this, but you get the point.
