### ISSUE TITLE
Unification of Overlays and Traits

### ISSUE THREAD

**Issue by mkistler** [OAI/OpenAPI-Specification#1843]
I'm opening this issue simply as a place to collect some ideas about how the concepts of [Overlays](#1722) and [Traits](#613) might be brought together.

In both proposals, I think the key notion is a "fragment", which I would describe as: a "sparse" sub-object of an OpenAPI definition.  In the Overlay proposal, a fragment is the `value` of an "Update Object" and has a type of `any`.

I think fragments -- which I would like to call "mixins" -- can have a more well-defined structure than just `any`.  If we use the `discriminator` approach already present in OpenAPI for "mixins", we can require (and validate) conformance to a particular structure.  In particular, we can require a mixin to be a "sparse" form of any well-defined OpenAPI object, e.g. Operation, Response, Parameters, or even the whole OpenAPI definition.

Mixins could be defined as just another flavor of "component".  So
```
components:
  mixins:
    pagable:
      type: operation            << so what follows should validate as a "sparse"* OpenAPI Operation object 
      < pageable parameters and response props in #613 >
```

Note *: "sparse" here means all props are optional

Mixins could then be included effectively anywhere in the API doc by reference:
```
  $mixin: "/components/mixin/pageable"
```

By virtue of the mixin type, it could be validated as allowed or not allowed at the point it is referenced.

Now Overlays can become simply a mechanism for inserting mixins and mixin references into an API document.  The JMESPath mechanism of overlays still provide the ability to apply a single update to multiple target objects using wildcards, but that update would now be expressed as simply adding a "mixin" to each of the target objects.

These are just strawman ideas and I do not claim to have thought them through any detail, but I hope they can serve as useful seeds for discussion.

**Comment by mkistler** [comment]
I listened back through the recording of the last meeting and attempted to catalog some of the issues to be addressed in this proposal.  Here's what I found:

- Add examples with before and after
- Describe how overlays would incorporate mixins
- Make the mixin `type` optional
  - When present, more detailed validation can be performed
  - When not present, the mixin could be applied to more than one object type
- Need to document how mixins are "applied"
  - Might need special rules to allow mixins for groups of elements, like parameters
  - Might need special rules or at least clear explanation of how mixins and $ref interact
  - Need to address how mixins can be used to remove elements from an API def
- How do mixins work with alternate schemas ??
- Can we define mixins in a way that facilitates their use in AsyncAPI ?
- Concerns about the use of JMES Path and whether it limits reuse

**Comment by mkistler** [comment]
## Leveraging mixins in overlays

If we create a "mixin" concept in the OpenAPI spec, we could leverage this in the Overlay spec by making mixins the mechanism by which overlays are applied. Adapting the example from #1722:

```
overlay: 1.0.0
info:
  title: Update many objects at once
  version: 1.0.0
updates:
- target: paths.*.get
    mixin:
      type: operation
      content:
        x-safe: true
- target: paths.*.get.parameters[?name=='filter' && in=='query']
    mixin:
      type: parameter
      content:
        schema:
          $ref: "/components/schemas/filterSchema"
```

Here, the structure and application of the "mixins" in the overlay doc would be defined in the OpenAPI spec, which would simplify the overlay mechanism for those already versed in OpenAPI.

**Comment by mkistler** [comment]
## How are mixins "applied"?

The basic idea is that the mixin "content" is JSON merged (or the YAML equivalent) with the element that immediately contains it. So with these definitions:

```
thing:
  foo: foo
  bar: bar
  $mixin: /components/mixins/bazqux

components:
  mixins:
    bazqux:
      content: 
        baz: baz
        qux: qux
```

the "realized" spec is:
```
thing:
  foo: foo
  bar: bar
  baz: baz
  qux: qux
```

I believe that this description could be equally applied to arrays. So for example:
```
things:
  - foo
  - bar
  - $mixin: /components/mixins/bazqux

components:
  mixins:
    bazqux:
      content: 
        - baz
        - qux
```

would become
```
things:
  - foo
  - bar
  - baz
  - qux
```
