### ISSUE TITLE
Add security to the components object

### ISSUE THREAD

**Issue by djpadz** [OAI/OpenAPI-Specification#1850]
Consider this snippet:

```yaml
components:
  securitySchemes:
    jwt:
      type: apiKey
      in: cookie
      name: JWT_TOKEN
    apiToken:
      type: http
      scheme: bearer
    httpBasic:
      type: http
      scheme: basic
```

If I want a set of requests to support each of these authentication methods in turn, I would have to add something like:

```yaml
    security:
    - jwt: []
    - apiToken: []
    - httpBasic: []
```

...to each one.  It would be far easier if the `components` object supported a `security` section, something like this:

```yaml
components:
  security:
    myAuths:
    - jwt: []
    - apiToken: []
    - httpBasic: []
```

...so that requests could just include:

```yaml
    security:
      $ref: '#/components/security/myAuths'
```
