### ISSUE TITLE
Better error from failed validation of parsing enum

### ISSUE THREAD

**Issue by anderamko** [OAI/OpenAPI-Specification#1871]
Generated code for such properties throws IllegalArgumentException in case it receives "color": "yellow". Exception is then wrapped in json processor in it's exception ultimately ending in HttpMessageConversionException. Both are difficult to parse, as at there's no way to handle all incoming places where it can come from and if it is not handled - 500 is thrown. 

```
color:
          type: string
          enum:
            - red
            - green
            - blue
```

Expectation - handle this in generated API, by default return 400, provide better error, allow user to override this behavior.
