### ISSUE TITLE
Callback object example has excess key

### ISSUE THREAD

**Issue by agarb7** [OAI/OpenAPI-Specification#1895]
Callback object example has excess `myWebhook` key:

```yaml
myWebhook:
  'http://notificationServer.com?transactionId={$request.body#/id}&email={$request.body#/email}':
    post:
      # ...
```

But specification say that callback object is map where each value is a **Path Item Object**. Thereby the example must be without extra level:

```yaml
'http://notificationServer.com?transactionId={$request.body#/id}&email={$request.body#/email}':
  post:
    # ...
```
