### ISSUE TITLE
[Feature Request] - Allow payload definition for JWT schema

### ISSUE THREAD

**Issue by ugurcemozturk** [OAI/OpenAPI-Specification#1971]
### Is your feature request related to a problem?
Yes. The clients will be able to know what they expect within the payload of the JWT. It will save time to parse the payload on the client-side.

### Describe the solution you'd like
In the security schemas sections, the developer should be able to provide the JWT payload as another sub-schema.
Something like:
```yaml
 securitySchemes:
    AppJwt:
      type: http
      scheme: bearer
      bearerFormat: JWT
            payload: '#/components/schemas/AppJwtPayload'
  schemas:
    AppJwtPayload:  
      type: object
      properties:
        userId:
          type: string
 ```
Thanks.

**Comment by ioggstream** [comment]
I'm unsure if

```
bearerFormat: JWT
  payload: bar
```

is valid yaml.

**Comment by ugurcemozturk** [comment]
Do you mean not a valid yml or openApi spec?

**Comment by ioggstream** [comment]
it's not valid yaml.

```
python -c '
import yaml;
yaml.load("""
a: 1
 b: 2
""")
'

yaml.scanner.ScannerError: mapping values are not allowed here
  in "<string>", line 3, column 3:
     b: 2

```

**Comment by DavidePastore** [comment]
I'd like to see this kind of feature available. Maybe the schema could be something like this:

```yaml
securitySchemes:
  AppJwt:
      type: http
      scheme: bearer
      bearerFormat: JWT
      properties:
            header: '#/components/schemas/AppJwtHeader'
            payload: '#/components/schemas/AppJwtPayload'
  schemas:
    AppJwtPayload:  
      type: object
      properties:
        userId:
          type: string
    AppJwtHeader:
      type: object
      properties:
        alg:
          type: string
        typ:
          type: string
```

Here I'm using different schemas for the header and the payload. I used the `properties` field name, but I think you could even find a better alternative if it doesn't fit your needs.
