### ISSUE TITLE
Ref a security scheme

### ISSUE THREAD

**Issue by SirWayne** [OAI/OpenAPI-Specification#2064]
Is it possible to reuse a security scheme? How can i ref a securityschema for resuability?

```
  securitySchemes:
    foo:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: 
          scopes: {}
```

This not working in a seperate file
```
security:
  - foo: []
```

Thanks
