### ISSUE TITLE
Feedback - Provide simplified YAML syntax for common cases

### ISSUE THREAD

**Issue by mtaylorfsmb** [OAI/OpenAPI-Specification#2070]
While I understand that in many cases we will be using a tool to auto-generate the OAI specification there are cases where we build them by hand such as prototyping a new API surface in an online editor. It would be nice if the YAML syntax allowed for a simpler syntax for some common cases. 

*Note: I'm proposing new alternative syntax for common cases. I do not recommend the existing format be changed but rather parsers be enhanced to detect simpler syntax cases and remap them automatically to the more verbose syntax.*

I'm aware of a couple after having prototyped a couple new APIs.

1. Arrays of objects. Currently the YAML syntax is this:
   ```yaml
   someProperty:
      type: array
      items:
         $ref: 'path to schema'
   ```
  For the (common) case of an array of pre-defined or schema-defined types it would be nice if we could just combine all this into `type` and let it be equivalent to the above. 
  ```yaml
  someProperty:
     type: array('path to schema')
     #or
     type: 'path to schema'[]
  ```

Common variants could also possibly be shortcut as well whereas the full syntax is available for more complex cases.

2. Schema refs. Currently the YAML synax for a schema reference is this:
    ```yaml
      content:
         application/json:
            schema:
               $ref: 'path to schema'
    ```
   For the common case of a reference object then allow it to be specified directly on the schema object.
  ```yaml
  content:
     application/json:
        schema: 'path to schema'
  ```
  Or maybe even shorter.
  ```yaml
  content:
     application/json: 'path to schema'
  ```

3. Required properties. It feels very odd to separate property definitions from their required state. 
   ```yaml
   required:
      - name
   properties:
      - name:
             type: string
   ```
Especially since required is a validation concept and validation properties are already on the property definition. Allow the required state of a property to be included as part of the property definition. This keeps them together and lessens the likelihood of someone forgetting them.
   ```yaml
  properties:
     - name:
           type: string
           required: true
   ```
 
4. Multiple content response fallthrough. In many cases an API will return a consistent error model for all non-success status codes. The only thing that may differ is the description of the status code.
  
 ```yaml
  responses: 
       '400':
          description: Bad request.
          content:
               application/json:
                   schema:
                       $ref: 'path to schema'
       '404':
          description: Item not found.
          content:
               application/json:
                   schema:
                       $ref: 'path to schema'
   ```

It would be nice to be able to combine several of them into one with just differing descriptions. Sort of like fallthrough in switch statements
   ```yaml
   response:
      '400': Bad request.
      '404': Item not found.
         content:
               application/json:
                   schema:
                       $ref: 'path to schema'
   ```

5. Common tags. Currently the `tags` element is on the individual operations. Since most of the time all the operations on a path are related it makes sense to be able to have a higher level tag on the path and then override it on a lower level operation if needed.
    ```yaml
      'products/{id}'
      tags: [ 'Products' ]
      get: ...
      post: ...
    ```
