### ISSUE TITLE
Improve type safety with restricted component references (OAS 4 proposal)

### ISSUE THREAD

**Issue by vearutop** [OAI/OpenAPI-Specification#2084]
JSON Schema does not define a concept of `$ref` usage in data values, neither it provides a way to ensure if resolved data value is valid. Nevertheless using `$ref` in data is popular and is used in OpenAPI. 

If it is not possible to validate the resolved value, we can at least have best effort validation that reference leads to a correct place.

OpenAPI spec since `v3` has a pre-defined place to store some kinds of referenced values: [`components`](https://github.com/OAI/OpenAPI-Specification/blob/92e15eba1d4591ebfe8c11898c48241e72854381/schemas/v3.0/schema.yaml#L133).

For example [`responses`](https://github.com/OAI/OpenAPI-Specification/blob/92e15eba1d4591ebfe8c11898c48241e72854381/schemas/v3.0/schema.yaml#L143-L149) are defined as follows:
```yaml
      responses:
        type: object
        patternProperties:
          '^[a-zA-Z0-9\.\-_]+$':
            oneOf:
              - $ref: '#/definitions/Reference'
              - $ref: '#/definitions/Response'
```

The problem here is that current schema allows `$ref` to lead to any place, not only to `#/components/responses/...`.

Semantically incorrect (but valid) schema with confused references:
```yaml
paths:
  /pets:
    get:
      parameters:
        - $ref: "#/components/responses/UnexpectedError"
```

We can make it harder to go wrong by restricting local references of schema components, for example `ResponseReference`:
```yaml
  ResponseReference:
    type: object
    required:
      - $ref
    patternProperties:
      '^\$ref$':
        type: string
        format: uri-reference
        oneOf:
          - pattern: '^#/components/responses/'
          - not:
              pattern: '^#/'
```

Such restriction (`pattern: '#/components/responses/'`) could also be employed for external references, though it may have too much of negative impact on flexibility.
