### ISSUE TITLE
Question: behavior of `default` in `allOf`

### ISSUE THREAD

**Issue by smikulcik** [OAI/OpenAPI-Specification#2166]
Since `default` places no validation rules on a given schema object, I can "Add a default" to an object without `default` set by using an allOf
```yaml
allOf:
  - $ref: '#/components/schemas/SchemaWithoutDefaultSet'
  - default: ValueOfDefaultIsSet
```

Though this raises the question, on the server end, what shall I set the default to in conflicting situations?
```yaml
type: string
allOf:
- default: a
default: b
```
or what if they both are in the `allOf`?
```yaml
type: string
allOf:
- default: a
- default: b
```
Technically, any json passed in is valid `{}` since default doesn't add any validation. But since the server must default to _both_, it appears to me that we are in an impossible situation.
