### ISSUE TITLE
How does one document a JSON attribute named "$ref" since it is a reserved keyword?

### ISSUE THREAD

**Issue by ethanbensonagc** [OAI/OpenAPI-Specification#2173]
I have a question about "$ref" and OpenAPI 3.0.0 specification. I am documenting a datamodel (I will call it "DataModel" for clarification) in "#/components/schemas/DataModel" which has a JSON attribute named "$ref". However, that is a reserved keyword in OpenAPI 3.0.0, used for referencing other areas of the OpenAPI document. How can I document my attribute "$ref" in the `properties` section of "#components/schemas/DataModel"? Is there an escape sequence that I can put before $ref? "$ref" is the name of an attribute, and does not reference a section in the OpenAPI 3.0.0 document.

Example: 

```
components:
   schemas:
      DataModel:
         type: "object"
         properties:
            $ref: 
               type: "string"
               example: "DocType|OtherDataModel|1351039-1"
```
