### ISSUE TITLE
Examples of a response not rendered when using examples block

### ISSUE THREAD

**Issue by JanChytry** [OAI/OpenAPI-Specification#2214]
Hey all,

I have encountered an issue in OpenAPI 3.0.2. when using _examples_ block to showcase multiple examples of a **single status code in response**. It shows example names, however, not the actual examples (is null every time). My spec is the following:

```yaml
      400:
        description: "Polygon does not meet criteria listed above."
        content:
          application/json:
            schema:
              properties:
                message:
                  type: string
            examples:
              PolygonNotValid:
                message: "Polygon format not valid"
              PolygonTooLarge:
                message: "Polygon is too large"
              PolygonNotL2A:
                message: "Polygon has no coverage"
```

It looks like this:
![image](https://user-images.githubusercontent.com/24588489/80038225-7ef41200-84f5-11ea-8871-3e2875bdb945.png)

**Comment by MikeRalphson** [comment]
It may be a bug in whatever tool you're using to visualise your OpenAPI document, but try adding 

```yaml
type: object
```

to your `schema`.

In general though, please raise tooling-related issues on the relevant repository. This repository is for the OpenAPI specification itself. You may also receive more answers on a general support forum such as StackOverflow. Thanks.

**Comment by hkosova** [comment]
@JanChytry the example definitions are missing the `value` keyword. Try this:
```yaml
            examples:
              PolygonNotValid:
                value:     # <------
                  message: "Polygon format not valid"
              PolygonTooLarge:
                value:     # <------
                  message: "Polygon is too large"
              PolygonNotL2A:
                value:     # <------
                  message: "Polygon has no coverage"
```
