### ISSUE TITLE
Would a parameter described as having format = date, but with a custom pattern, be a violation of this specification?

### ISSUE THREAD

**Issue by IanKemp** [OAI/OpenAPI-Specification#2286]
Consider this definition:

```
startDate:
  type: string
  format: date
  pattern: "DD-MM-YYYY" # not RFC 3339-compliant
```

This field claims to be of type date, but its pattern does not comply with RFC 3339's specification for date formatting. Would such a definition be a violation of the OpenAPI specification? If so, what would a valid definition be?
