### ISSUE TITLE
Deprecate Parameter.content in favor of JSON Schema's contentSchema?

### ISSUE THREAD

**Issue by hkosova** [OAI/OpenAPI-Specification#2289]
JSON Schema 2019-09 has the [`contentSchema`](https://json-schema.org/draft/2019-09/json-schema-validation.html#rfc.section.8.5) keyword whose purpose and functionality seems to be the same as that of  [`content`](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.1.0.md#parameterContent) in Parameter Objects.

Should Parameter Object's `content` be deprecated in favor of JSON Schema's `contentSchema` keyword?

Example:
```
# Query parameter representation before URL encoding
?data={"foo":"hi","bar":123}
```

OAS 3.0:
```yaml
parameters:
  - in: query
    name: data
    content:
      application/json:
        schema:
          type: object
          properties:
            foo:
              type: string
              example: hi
            bar:
              type: integer
              example: 123
```

OAS 3.1 + contentSchema:
```yaml
parameters:
  - in: query
    name: data
    schema:
      type: string
      contentMediaType: application/json
      contentSchema:
        type: object
        properties:
          foo:
            type: string
            example: hi
          bar:
            type: integer
            example: 123
```
