### ISSUE TITLE
Support mutiple api keys as a new security type

### ISSUE THREAD

**Issue by woostundy** [OAI/OpenAPI-Specification#2292]
I find that OpenAPI3 has supported mutiple api keys , but the current solution for "mutiple api keys" is weird. (https://swagger.io/docs/specification/authentication/api-keys/)

In my understanding, a `security scheme` means a whole set of security solution, just like "OAuth", "HTTPBasic" , etc.
But in this case, the scheme just means a api key. And I think the `security scheme` should be independent, and it doesn't need the settings in the `path operations` (delete leading dash to make them work together).

Is it possible to add a new uniform `security type` for mutiple api keys? On this basis I can define other custom securitys, such as "HMAC".
 
In my imagination, it could be something like:
```
components:
  securitySchemes:
    ApiKeyAuth:        # arbitrary name for the security scheme
      type: apiKeys
      keys:
         - in: header       # can be "header", "query" or "cookie"
           name: X-API-Key  # name of the header, query parameter or cookie
         - in: header
           name: X-API-Timestamp 
         - in: header
           name: X-API-Signature

```
