### ISSUE TITLE
dictionary key descriptions/schema (additionalProperties)

### ISSUE THREAD

**Issue by theoephraim** [OAI/OpenAPI-Specification#2294]
I didnt see any way to add documentation/info about the keys that can be used when using dictionaries (ie "additionalProperties")

In the swagger docs example [here](https://swagger.io/docs/specification/data-models/dictionaries/), it appears the valid keys are all 2 letter ISO language codes. It would be great to be able to specify for these keys:
- a name/label to be used in display rather than something generic like "property name*" (ex: "language code")
![image](https://user-images.githubusercontent.com/1158956/88094599-b3a15500-cb48-11ea-8d85-afc589ea0621.png)
- a description (ex: "lowercase 2 letter ISO 639-1 Code")
- schema info ex: `{ type: "string", pattern: '^[a-z]{2}$' }`

Also as a sidenote, the name "additionalProperties" isn't super intuitive, but probably somewhat settled to change it now...

**Comment by theoephraim** [comment]
Note - the name/label part has been implemented as a an extension in [ReDoc](https://github.com/Redocly/redoc/blob/master/docs/redoc-vendor-extensions.md#x-additionalpropertiesname)

**Comment by hkosova** [comment]
@theoephraim 
> It would be great to be able to specify for these keys:
> * ...
> * a description (ex: "lowercase 2 letter ISO 639-1 Code")
> * schema info ex: `{ type: "string", pattern: '^[a-z]{2}$' }`

This will be possible in OAS 3.1 using `patternProperties`:

```yaml
type: object
patternProperties:
  '^[a-z]{2}$':    # <--- key regex
    type: string   # <--- value schema
additionalProperties: false
```

or `propertyNames`:
```yaml
type: object
propertyNames:
  pattern: '^[a-z]{2}$':
  description: lowercase 2 letter ISO 639-1 Code
additionalProperties:
  type: string
```
