### ISSUE TITLE
position-matched array items schema

### ISSUE THREAD

**Issue by bmaranville** [OAI/OpenAPI-Specification#2331]
Hello, I would like to write a schema in which the items of an array have a sub-schema which is determined by their position in the array (this is supported in json-schema 2019-09)
If I write e.g. 
```yaml
components:
  schemas:
    wire:
      type: array
      items:
      - type: integer
      - type: string
```
In order to specify arrays like [0, "output"], will this work in OAS 3.1.0?

**Comment by MikeRalphson** [comment]
Yes, this will work in OAS 3.1

**Comment by handrews** [comment]
Note that by OAS 3.1 final (which will use the _next_ JSON Schema draft, assuming all goes according to plan), this will be written as:

```YAML
components:
  schemas:
    wire:
      type: array
      prefixItems:
      - type: integer
      - type: string
```

due to ongoing confusion over having two different syntaxes for the `items` keyword.  `prefixItems` takes over the array form.  In this case, there is nothing after the two-item "prefix", making the keyword name a little odd, but every single naming approach we came up with was awkward in some way or another, and this is what we settled on.

This should make it a bit easier for tooling, which will not have to inspect the type of the value of `items` to figure out what it's doing.
