### ISSUE TITLE
Model with name as RESOURCE is not getting generated.

### ISSUE THREAD

**Issue by bipin-yadav** [OAI/OpenAPI-Specification#2332]
Having schema like this

```yaml
components:
  schemas:
    Resource:
      type: object
      properties:
        srcId:
          type: string
        role:
          type: string
        equip:
          type: string
```

Api interface is taking the reference of the Spring  resource and not generating the Resource**** e.g ResourceModel pojo class.
