### ISSUE TITLE
Usage of required schema property: is this correct?

### ISSUE THREAD

**Issue by spacether** [OAI/OpenAPI-Specification#2385]
So I am having trouble understanding when a schema's required boolean value is used.

## Parameter
Let's say a parameter uses a ref to a schema:
```
  name: "header",
  in: "header",
  description: "token to be passed as a header",
  required: true,
  schema:
    ref: '#/components/schemas/Header'
```
required is set to true in the header parameter definition.
So whether or not schema Header has required set does not matter, right?

## Object Properties
```
type: object
properties:
  id:
    type: integer
    format: int64
  name:
    required: True
    type: string
required:
- id
```
required is set to true in name definition but it is not required because it is not included in the object.required list of required property names.

## Array Items
```
animals:
  type: array
  items:
    required: true
    type: string
```
Required has no impact here if an item exists in the array it must conform to this definition.

## Additional Properties
```
type: object
properties:
additionalProperties:
  required: true
  type: string
```
Required has no impact here if an item exists in the array it must conform to this definition.

## Response Bodies
```
{
  "description": "user to add to the system",
  "required": True
  "content": {
    "application/json": {
      "schema": {
        "$ref": "#/components/schemas/User"
      },
      "examples": {
          "user" : {
            "summary": "User Example", 
            "externalValue": "http://foo.bar/examples/user-example.json"
          } 
        }
    },
```
Required is included in request bodies so the required value in User has no impact.

## Response Bodies
```
{
  "description": "A complex object array response",
  "content": {
    "application/json": {
      "schema": {
        "type": "array",
        "items": {
          "$ref": "#/components/schemas/VeryComplexType"
        }
      }
    }
  }
}
```
Schema type is directly used.
Is this the only place where schema.required is used?
So if MediaType has required added to it then we can remove required from the Schema object?
