### ISSUE TITLE
security scheme apiKey in body form data parameter

### ISSUE THREAD

**Issue by johakoch** [OAI/OpenAPI-Specification#2419]
It is possible to define a security scheme as
```
QueryKey:
  type: apiKey
  in: query
  name: myparam
```
corresponding to
```
parameters:
  - name: myparam
    in: query
    required: true
```
while the first approach adds the notion that the required parameter is related to security.

However there seems to be no way to define a security scheme about a required parameter in an `application/x-www-form-urlencoded` body adding the same security notion.

**Comment by MikeRalphson** [comment]
Can you clarify if this is a question or a feature request? If the latter, do you have an actual API which uses an API key in a request body?

**Comment by johakoch** [comment]
The question: Are there reasons against such a feature?

Regarding an actual API:

The OAuth2 token endpoint requires the client to authenticate via
* Basic Auth using `client_id`:`client_secret`, OR
* sending `client_id` AND `client_secret` parameters in the `POST` request

This could be specified as
```
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    ClientIdPost:
      type: apiKey
      in: ???
      name: client_id
    ClientSecretPost:
      type: apiKey
      in: ???
      name: client_id
security:
  - BasicAuth: []
  - ClientIdPost: []
    ClientSecretPost: []
```
