### ISSUE TITLE
Do server variables allow unencoded slashes?

### ISSUE THREAD

**Issue by hkosova** [OAI/OpenAPI-Specification#2421]
This is somewhat related to #2204 and https://github.com/OAI/OpenAPI-Specification/pull/2218. It's been clarified that path parameters don't allow unescaped slashes, but what about server variables?

Consider this example:
```yaml
servers:
  - url: "https://example.com/{subpath}reports/"
    variables:
      subpath:
        default: ''
        enum:
          - ''
          - 'abc/123/'
          - 'abc/456/'
```

Are these valid values for a server variable?
If yes - what is the resulting server URL for `subpath`=`abc/123/`? --
```
https://example.com/abc/123/reports/
 or
https://example.com/abc%2F123%2Freports/
```

<br/>

In other words, is the example above a proper way to vary subpaths using server variables, or should this example be rewritten as follows? --
```yaml
servers:
  - url: "https://api.example.com/reports/"
  - url: "https://api.example.com/abc/{id}/reports/"
    variables:
      id:
        default: ''
        enum:
          - '123'
          - '456'
```
