### ISSUE TITLE
How do I describe a nested array of arbitrary depth in my API docs?

### ISSUE THREAD

**Issue by telamonian** [OAI/OpenAPI-Specification#2426]
I have a [backend](https://github.com/jupyterlab/jupyterlab-hdf5) that fetches data from HDF5 files. One of my endpoints, [hdf/data](https://jupyterlab.github.io/jupyterlab-hdf5/#/paths/~1hdf~1data~1{fpath}{?uri}{?ixstr}{?subixstr}{?min_ndim}/get), returns the raw array data from a dataset. Currently, in the `schema` section of my `api.yaml` doc I define the [`data`](https://github.com/jupyterlab/jupyterlab-hdf5/blob/2415d9a10e96a61e396271691ea4161acfe2182c/jupyterlab_hdf/api/api.yaml#L250) type as:

```yaml
    data:
      description: "a chunk of raw array data from an hdf dataset. May be of any dimensionality"
      type: array
      items:
        type: array
        items:
          type: number
```

So this says that all data will be a nested array of `number` of depth 2. This is not correct; the depth of the returned array will match the dimensionality of the dataset that's being fetched from, and so can actually be any non-negative integer value.

Is there a good way to handle this kind of type that has unknown or arbitrary nesting in an openapi doc?
