### ISSUE TITLE
How to describe certain numeric values that have special meaning?

### ISSUE THREAD

**Issue by Simran-B** [OAI/OpenAPI-Specification#2455]
Imagine you want to configure a service, which has an API to set the maximum amount of memory to use for its operations:

```yaml
type: object
properties:
  memoryLimit:
    type: integer
    minimum: -1
    maximum: 1024
```

The lowest two allowed numbers are somewhat special:

Value | Description
--:|:--
`-1` | Auto, use 75% of the detected system memory (default)
`0` | No memory limit (100%)
`1`..`1024` | Amount of memory in megabytes (absolute)

Is the following the canonical way to model such an API? Are there any other ways?

```yaml
type: object
properties:
  memoryLimit:
    type: integer
    default: -1
    oneOf:
      - const: -1
        description: Auto, use 75% of the detected system memory
      - const: 0
        description: No memory limit
      - minimum: 1
        maximum: 1024
        description: Amount of memory in megabytes
```
