### ISSUE TITLE
XML mapping for enum elements

### ISSUE THREAD

**Issue by Zash** [OAI/OpenAPI-Specification#2497]
Use case is XML where one of several states are indicated via presence of one of several possible elements, so that the name of the element is the relevant value. Examples from XMPP include [chat states](https://xmpp.org/extensions/xep-0085.html) (e.g 'is typing', 'stopped typing' states), or the [extensive list of error conditions](https://xmpp.org/rfcs/rfc6120.html#stanzas-error-conditions).

Given this schema:
```yaml
type: object
xml:
  name: wrap
properties:
  state:
    type: string
    enum:
    - foo
    - bar
    - baz
    xml:
      x_attribute_is_value: true # WIP name
```
this data:
```json
{"state":"bar"}
```
would map to:
```xml
<wrap>
  <bar/>
</wrap>
```

When applied to a `boolean` property this could be used to map `true` to the element being present and `false|null` to it being absent.

**Comment by MikeRalphson** [comment]
I think your example has `enum` and `state` in the reversed positions? I'm not totally sure of the general usefulness of your proposed `attributeIsValue` property... Couldn't you just do:

```yaml
type: object
xml:
  name: wrap
oneOf:
  - properties:
      foo:
        type: string
        minLength: 0
  - properties:
      bar:
         type: string
        minLength: 0
  - properties:
      baz:
        type: string
        minLength: 0
```

unless you had a need for a JSON representation of the same schema to actually use a an `enum`?
