### ISSUE TITLE
Support interdependencies between query parameters

### ISSUE THREAD

**Issue by cwarny** [OAI/OpenAPI-Specification#256]
It would be great to be able to specify interdependencies between query parameters. In my app, some query parameters become "required" only when some other query parameter is present. And when conditionally required parameters are missing when the conditions are met, the API fails. Of course I can have the API reply back that some required parameter is missing, but it would be great to have that built into Swagger.

**Comment by webron** [comment]
This is something that's very complicated to describe elegantly. Feel free to suggest a format that you think would be suitable for it.

**Comment by cwarny** [comment]
My suggestion would be as follows: instead of having the field "required" boolean, make it either boolean or an array of references to other parameters. If you put `required: true`, it would have to always be present. If you put `required: [$a, $b]`, it means that this parameter needs parameters `a` and `b` to be present.

**Comment by mohsen1** [comment]
How you describe an endpoint where one of it's parameters is required if another query parameter is equal to a string or is larger than a number? This can get very complicated. I would say if a parameter is required *sometimes* it's not required.

**Comment by cwarny** [comment]
I'd say either keep it simple and only allow simple interdependencies like, if `a` is present, then `b`is required (i.e. `required: [$a, $b]`), or define simple operations like, `required: [$a>3, $b=="hello", "world" in $c]`. I would favor keeping it simple, but then I have to admit that my only response to "why not keep it even simpler (i.e. as it is now) and only have a boolean `required`" is: it's a matter of how useful more sophistications are. For me, having simple interdependencies is useful and better than just a boolean `required`, but I don't think I need more complicated stuff. Other people might disagree.

**Comment by webron** [comment]
While this may be a solution, it can also be a validation nightmare. Definitely not something that can be done with a json schema.

**Comment by iisurge** [comment]
maybe something like
`"required": false,
"depends": [
$a,
$b
]`

**Comment by rcork** [comment]
Don't forget the "OR" dependency. I have a service where one of two query parameters must be present but it doesn't matter which one. For now we are just documenting the interdependency and using a error schema with the appropriate code/message but would be preferable to have this defined in the contract up front.

**Comment by fractalawareness** [comment]
+1 for **cwarny** simple suggestions

**Comment by filipnowakswissre** [comment]
My use-case is to have only one property of the parameter required, but from the array of the definitions.

**Comment by craig-bayley** [comment]
You can solve the OR use case already using an enumerated filter_type paired with a filter_value query parameter(s).

Example: 
        - name: filter_type
          in: query
          description: What type of values to filter on
          required: false
          type: string
          enum: [location, service, name]
          default: location
        - name: filter_value
          in: query
          description: The value to apply to the filter_type. Should match what was in the filter, i.e. if filtering on location use a location name.
          required: false
          type: string
          default: all

**Comment by filipnowakswissre** [comment]
wow, good one, thanks

**Comment by ePaul** [comment]
@craig-bayley could you format your example as YAML, please? Just adding

    ```yaml
    [...]
    ```
around it makes it much easier to read.

**Comment by craig-bayley** [comment]
@ePaul Thanks for the tip. Done.

**Comment by scottmas** [comment]
+1 Something like this would be very nice.

**Comment by fehguy** [comment]
Folks just to set expectations, we're not doing this in the initial cut of 3.0

**Comment by handrews** [comment]
> some query parameters become "required" only when some other query parameter is present

The JSON Schema `"dependencies"` keyword does exactly this.  The `"if"`/`"then"`/`"else"` keywords (json-schema-org/json-schema-spec#180) that seem likely to go into a near-future draft would also accomplish this (probably more clearly for most people).

**Comment by webron** [comment]
I don't see how JSON Schema would be relevant for this at all.

**Comment by handrews** [comment]
@webron further up you said:

> Definitely not something that can be done with a json schema.

so I assumed that meant that JSON Schema was at least _potentially_ relevant, which meant that I should point out that JSON Schema can in fact do this.  I think you were specifically referring to an approach based on `"required"` which would not be valid JSON Schema, but there is JSON Schema support for this use case.

**Comment by webron** [comment]
Gotcha. That referred to the validation of it, not the representation of it in the spec. I assumed you were referring to the representation, making it my bad.

**Comment by AlwaysAbhl001** [comment]
When it going to be on air ? much needed one.

**Comment by jainpradeep100** [comment]
I have need to generate @Context HttpHeader parameter by Swagger.  Is it possible or not? If possible then how it would be accomplish.

**Comment by webron** [comment]
@jainpradeep100 for tool-specific questions, please ask in its respective support channel, not here.

**Comment by HappyTreesDev** [comment]
Required could hold a simple true, false, or it could hold an object like:

```json
"required": [{
    "name" : "name of other param",
    "relationship" : "present, missing, or maybe some equation",
    "grouping" : "AND Vs OR"
}]
```

Something along the line of that where required would take an array of requirement objects that define the other relationships that the param has with other params.

**Comment by AndreKR** [comment]
I don't have enough experience with the OpenAPI specs to say if this is a good idea, but how about having an array of constraints, similar to how you would place CHECK constraints on a database schema.

Building upon [this](https://swagger.io/docs/specification/describing-parameters/#dependencies) example, something like:

```yaml
paths:
  /report:
    get:
      parameters:
        - name: rdate
          in: query
          schema:
            type: string
          description: >
             A relative date range for the report, such as `Today` or `LastWeek`.
             For an exact range, use `start_date` and `end_date` instead.
        - name: start_date
          in: query
          schema:
            type: string
            format: date
          description: >
            The start date for the report. Must be used together with `end_date`.
            This parameter is incompatible with `rdate`.
        - name: end_date
          in: query
          schema:
            type: string
            format: date
          description: >
            The end date for the report. Must be used together with `start_date`.
            This parameter is incompatible with `rdate`.
      constraints:
        - type: required_either_or
          either: [rdate]
          or: [start_date, end_date]
```

This way all kinds of relationships can be expressed, they can be extended in a backwards-compatible manner and shorthands for common scenarios make it intuitive to read.

**Comment by handrews** [comment]
I'm probably going to annoy people by being a broken record, but if `parameters` was a JSON Schema that was required to be of type "object", then you could express all of this in JSON Schema easily enough.  In the forthcoming draft-07, `"if"`/`"then"`/`"else"` makes it a lot more readable and easier to work with in code than implementing conditionals with `"oneOf"`.

**Comment by AndreKR** [comment]
I didn't notice I had picked an example where it's not a JSON Schema, in fact my `constraints` idea apply equally to for example `requestBody`, which is kind of compatibel with JSON Schema. So `parameters` not being a JSON Schema is a related but separate issue.

That said, my experience with JSON Schema and conditionals is limited to the abilities of [ajv-keywords](https://github.com/epoberezkin/ajv-keywords), but to be honest that was disappointing. I expected to be able to require and to forbid the existence of keys, values, default values and sub-schemas, using either the existence of keys or their values as a condition. It turned out half of those constraints are impossible to implement with ajv-keyword's if/then/else.

Is the JSON Schema proposal mightier?

**Comment by handrews** [comment]
@AndreKR ajv-keywords' if-then-else is the preliminary implementation, which got lots of positive feedback.  But please feel free to comment at https://github.com/json-schema-org/json-schema-spec/pull/375

I think we can work most of those out but let's not clutter up OAI's issue with that discussion :-)

**Comment by sivaramankannan** [comment]
This is something I have been looking for a long time. I like the idea of interoperating with the JSON schema for achieving this - please let me know the plans for this feature and if its on the cards.

**Comment by mewalig** [comment]
In the interest of flexibility... how about implementing the ability to define a third-party syntax (like jq)? From the perspective of the OpenAPI, the specification would merely require that it is specified as a third-party type, and contains the type identifier (e.g. "jq"), and corresponding filter/condition definition (e.g. the jq filter). Long shot but figured I'd ask...

**Comment by MikeRalphson** [comment]
@mewalig I appreciate you mentioned `jq` only as an example, but as far as I am aware, the `jq` syntax is not standardised anywhere, it only exists on the `jq` [website documentation pages](https://stedolan.github.io/jq/manual/), and `jq` itself is only available as a standalone program, not even a library for other tools to use.

That said, I'd be interested in seeing an example of the sort of syntax which you think might help with this issue. 

Nb: allowing multiple third-party syntaxes risks, as in #764, fragmenting the tooling community as to which tools support which syntaxes.

**Comment by mewalig** [comment]
@MikeRalphson I agree with those concerns and assume they stem from a requirement, were OpenAPI to go down this path, that the syntax of any supported third-party filter/condition/content be pre-defined and incorporated (directly or by reference) into the OpenAPI standard?

If so, one potential approach would be to offer this functionality as a further supported option of an [OpenAPI extension](https://swagger.io/docs/specification/openapi-extensions/) or some other way to essentially require various items to be provided in order for the third-party syntax to conform.

As a limited-scope example, a "jq" extension / package might require that the jq syntax is made available in some specified form. The term "made available" could be realized by any/all of
* included in the data itself. This would be most portable and flexible
* a URL to an OpenAPI-hosted location
* a URL to a non-OpenAPI-hosted location

Regardless of which of the above are supported, there would need to be a grammar specification that is defined in some form such as BNF or similar-- and there would need to be a "meta" grammar specification for the grammar specification. If the spec must be sufficient not just to validate rule syntax but also to validate the rule in the specific context in which it is being used, then the meta-grammar would also need to support a mechanism to identify items it must interpret, when validating, as data elements (for example, the jq rule ```.parameter.abc == "hello"``` is valid syntax, but would be invalid in the context of input that is not a dictionary with a member called "parameter" that is a dictionary type. If OpenAPI would require that this latter kind of error be detectable, the grammar spec would need some information to instruct the parser how to know that ".parameter.abc" refers to such a member).

Apart from specifying the grammar, applying a rule could be fairly straightforward. For example, a constraint requiring that the GET param "abc" equals "hello" might look something like the below:

```
paths:
  /report:
    get:
      parameters:
        abc:
          - type: array
          ...
      constraints:
        - type: extension
          name: arbitrary_name
          input_type: json # specify that the extension will consume the data as JSON. Could also be XML or other predetermined supported types
          content: .parameters | .abc[0] == "hello"
syntaxes:
  arbitrary_name:
    grammar: <grammar definition goes here>
```

**Comment by hkosova** [comment]
> @AndreKR commented on Aug 31, 2017:
> Building upon [this](https://swagger.io/docs/specification/describing-parameters/#dependencies) example, something like:
> ```yaml
> paths:
>   /report:
>     get:
>       parameters:
>         - name: rdate
>           in: query
>           schema:
>             type: string
>           description: >
>              A relative date range for the report, such as `Today` or `LastWeek`.
>              For an exact range, use `start_date` and `end_date` instead.
>         - name: start_date
>           in: query
>           schema:
>             type: string
>             format: date
>           description: >
>             The start date for the report. Must be used together with `end_date`.
>             This parameter is incompatible with `rdate`.
>         - name: end_date
>           in: query
>           schema:
>             type: string
>             format: date
>           description: >
>             The end date for the report. Must be used together with `start_date`.
>             This parameter is incompatible with `rdate`.
>       constraints:
>         - type: required_either_or
>           either: [rdate]
>           or: [start_date, end_date]
> ```

A possible workaround that exists in OpenAPI 3.0 is to define the interdependent parameters as a single object-type parameter with `style: deepObject`, and use the appropriate JSON Schema constraints (`oneOf`, `anyOf`, etc.) within the object schema.

```yaml
paths:
  /report:
    get:
      parameters:
        - in: query
          name: date_range
          required: true
          schema:   # either ?rdate=...  or ?start_date=...&end_date=...
            type: object
            oneOf:
              - properties:
                  rdate:
                    type: string
                    description: A relative date range, such as `Today`.
                required: [rdate]
                additionalProperties: false
              - properties:
                  start_date:
                    type: string
                    format: date
                  end_date:
                    type: string
                    format: date
                required: [start_date, end_date]
                additionalProperties: false
          style: deepObject
          explode: true
```
But this feels more of a hack than a real solution. Also, handling this in codegen will probably be tricky.

**Comment by handrews** [comment]
@hkosova 

> and use the appropriate JSON Schema constraints

This is exactly why URI Template parameters in JSON Hyper-Schema are handled with a single schema (the `hrefSchema` keyword plus some supporting modifiers).  It treats the URI Template as an object in the data model, and applies `hrefSchema` to the object as a whole.  So yes, you almost always end up having to say `{"properties": {...}"}` which is a tiny bit of annoying boilerplate, but it means that every single feature of JSON Schema works with parametrized URIs.  `hrefSchema` covers path and query parameters.

Likewise `headerSchema`, which would cover header and (indirectly) cookie parameters, although you can't mix it with `hrefSchema`.  So at least in the current draft you can't have dependencies between `hrefSchema` parameters and `headerSchema` parameters.

This would obviously have to be an OpenAPI 4 proposal, and even then might be too fundamentally against OAS's architectural principles, but the Parameter object could easily be replaced by a schema augmented with an extension vocabulary for for things like `deepObject` and other non-RFC 6570 / non-standard-JSON-Schema concepts.

**Comment by cernael** [comment]
Would allowing composition for the parameters object be an option? I'm thinking something like:
```yaml
paths:
  /pets/{pet_type}/{name}:
    get:
      summary: retrieve pet
      description: returns pet object
      parameters:
        oneOf:
          - 
            - name: pet_type
              in: path
              required: true
              description: type of pet
              schema:
                enum:
                  - cat
            - name: name
              in: path
              required: true
              description: name of cat
              schema:
                enum:
                  - Quaxo
                  - Corricopat
                  - Jellylorum
          - 
            - name: pet_type
              in: path
              required: true
              description: type of pet
              schema:
                enum:
                  - dog
            - name: name
              in: path
              required: true
              description: name of dog
              schema:
                enum:
                  - Buster
                  - Sture
                  - Old Yeller
```
