### ISSUE TITLE
Getting StringStri instead of only string 

### ISSUE THREAD

**Issue by bnisarg1** [OAI/OpenAPI-Specification#2575]
Hi, we are getting stringstri instead of string type

Issue: 
when minlength  is 7 - we get "strings" in preview
when minlength  is 8 - we get "stringst" in preview
when minlength  is 9 - we get "stringstr" in preview
Similary it continues.

expected - only "string"

Step to reproduce issue:
```
components:
 schemas:
   Manufacturer:
      required:
        - name
      properties:
        name:
          type: string
          minLength: 10
          maxLength: 2048
```

In Preview getting following 
```
{
  "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "name": "Widget Adapter",
  "releaseDate": "2021-05-17T06:52:27.542Z",
  "manufacturer": {
    "name": "stringstri",
    "homePage": "string",
    "phone": "string"
  }
}
```
