### ISSUE TITLE
[apiKey] auth by two apikey together

### ISSUE THREAD

**Issue by wang-sy** [OAI/OpenAPI-Specification#2612]
I want to use two filed together, like :
- `X-Api-Key`: apiKey.
- `X-Real-IP`: clientIP.

So I write:
```yaml
apiKeyAuth:
  name: X-Api-Key
  type: apiKey
  in: header
apiKeyAuthClientIP:
  name: X-Real-IP
  type: apiKey
  in: header

security:
  - apiKeyAuth: []
    apiKeyAuthClientIP: []
```

but the generated function is :
```go
APIKeyAuthAuth func(string) (*identity.LoginRes, error)
APIKeyAuthClientIP func(string) (*identity.LoginRes, error)
```

I expect to get code Like this :
```go
func APIKeyAuth(apiKey, clientIP string) (*identity.LoginRes, error) {}
```

what can I do ?
