### ISSUE TITLE
Multi type for properies OAS

### ISSUE THREAD

**Issue by phanthaiduong22** [OAI/OpenAPI-Specification#2663]
Assume I have a JSON look like this
```[
    {
        "key": "number",
        "value": 1
    },
    {
        "key": "website",
        "value": "google.com"
    }
]
```
Something.yaml
``` 
type: object
title: Something
properties:
  key:
    description: The key of something.
    type: string
  value:
    description: The value of something. (can be any type)
    type: ?
required:
  - field
 ```

How can I write type for the value which I don't have specific type
