### ISSUE TITLE
Broken examples

### ISSUE THREAD

**Issue by maxlinc** [OAI/OpenAPI-Specification#267]
Several of the examples in this repo are invalid according to:
- `swagger-tools validate`
- The Swagger editor
- The validator badge service (although I'm not sure it's working)

For example, the uber.yaml example shows these errors in via swagger-tools or the editor:

```
$ swagger-tools validate examples/v2.0/yaml/uber.yaml

API Errors:

  #/definitions/Activities/properties/history: Missing required property: items
  #/paths/~1products/get/responses/200/schema/items/$ref: Not a valid JSON Reference
  #/paths/~1products/get/responses/default/schema/$ref: Not a valid JSON Reference
  #/paths/~1estimates~1price/get/responses/200/schema/items/$ref: Not a valid JSON Reference
  #/paths/~1estimates~1price/get/responses/default/schema/$ref: Not a valid JSON Reference
  #/paths/~1estimates~1time/get/responses/200/schema/items/$ref: Not a valid JSON Reference
  #/paths/~1estimates~1time/get/responses/default/schema/$ref: Not a valid JSON Reference
  #/paths/~1me/get/responses/200/schema/$ref: Not a valid JSON Reference
  #/paths/~1me/get/responses/default/schema/$ref: Not a valid JSON Reference
  #/paths/~1history/get/responses/200/schema/$ref: Not a valid JSON Reference
  #/paths/~1history/get/responses/default/schema/$ref: Not a valid JSON Reference
  #/definitions/Activities/properties/history/$ref: Not a valid JSON Reference

API Warnings:

  #/definitions/Product: Definition is defined but is not used: #/definitions/Product
  #/definitions/PriceEstimate: Definition is defined but is not used: #/definitions/PriceEstimate
  #/definitions/Profile: Definition is defined but is not used: #/definitions/Profile
  #/definitions/Activity: Definition is defined but is not used: #/definitions/Activity
  #/definitions/Activities: Definition is defined but is not used: #/definitions/Activities
  #/definitions/Error: Definition is defined but is not used: #/definitions/Error

12 errors and 6 warnings
```

**Comment by maxlinc** [comment]
Note: I setup gulp and mocha as part of the travis-ci build to validate examples a while ago. At that time swagger-tools didn't exist - or at least didn't have an easy to use CLI validator for Swagger v2 yet. Now that it's an easy to use, thorough validator that is used by swagger-editor I think it would be good to hook into the Travis build so it validate changes to examples.

@whitlockjc do you think you could hook swagger-tools into the Travis build to validate changes to examples/*? If you don't have time I can send a PR with a naive hookup (i.e. bash for loop), but I'm not a javascript guy so wanted to see if you had an opinion about validation via pure CLI vs something like a grunt/gulp task or mocha tests.

**Comment by webron** [comment]
@maxlinc - I'm working on fixing the samples, and most of them should be fixed in the 2.0_fixes branch.

Did you encounter the problems with the YAML samples or also the JSON ones? I'm very likely going to remove the whole YAML samples, or possibly move them to the swagger-editor repo as they are really only relevant there.

**Comment by maxlinc** [comment]
Please don't remove the YAML examples, they're very useful and not just for swagger-editor. I agree we shouldn't need to *maintain* both sets, but I think the solution is to write one and then convert it to the other - and validate both.

Personally I'd prefer to write YAML and generate JSON, because YAML is designed designed for humans: it's easier to read, easier to write, and it allows comments. In my opinion writing Swagger in JSON and then converting to YAML is like writing a README.html and then using pandoc to convert it to README.md. Even if you ultimately *need* HTML it doesn't mean you should write it.

The comments are especially useful for examples, and even more so when you consider tools like [groc](http://nevir.github.io/groc/) or [docco](jashkenas.github.io/docco/) to turn commented YAML sample into HTML documentation, or a tool I'm finishing up to turn commented YAML into Markdown. 

I'm not saying we *should* document the YAML examples and generate documentation, but here are some examples just to show the power and flexibility of writing examples in YAML.

Adding these comments to the uber example:

```yaml
# ## Uber Example
#
# This is an example of the [Uber API](http://blog.uber.com/api)
# as a demonstration of an API spec in YAML.
swagger: "2.0"
info:
  title: Uber API
  description: Move your app forward with the Uber API
  version: "1.0.0"
# The `host` should be the production domain of your service. It's recommended
# that [Swagger-compatible tools][tools], especially ones designed for testing
# like [Flex][flex] or [Pacto][pacto] allow you to override the host for testing
# purposes, so you could set it to something like `stage.api.uber.com` without
# editing the Swagger file.
#
# Note the host does not allow [URI templating][templating].
#
# [tools]: https://github.com/swagger-api/swagger-spec#additional-libraries
# [flex]: flex-swagger.readthedocs.org
# [pacto]: https://github.com/thoughtworks/pacto
# [templating]: https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#path-templating
```

Would be rendered in groc's parallel style for displaying commented YAML as:
![screen shot 2015-02-07 at 3 58 57 pm](https://cloud.githubusercontent.com/assets/896878/6093935/5dcc89de-aee2-11e4-8edb-c6befa800cb2.png)

Other tools have inline styles if you don't like parallel, and inline images are even possible though in my experience they usually don't look great (especially in the parallel style). Links to images are probably better, but here's an example anyways. 

This YAML:

```yaml
      summary: Product Types
      description: The Products endpoint returns information about the Uber products offered at a given location. The response includes the display name and other details about each product, and lists the products in the proper display order.
      parameters:
        - name: latitude
          in: query
          description: Latitude component of location.
          required: true
          type: number
          format: double
        - name: longitude
          in: query
          description: Longitude component of location.
          required: true
          type: number
          format: double
# The parameters defines the parameters that are used in by the operation, and is also used to generate
# the forms in Swagger-UI or Swagger Editor that allow people to try your operation. The parameters above would
# produce this form in Swagger Editor:
#
# ![form](https://cloud.githubusercontent.com/assets/896878/6093974/653be95c-aee3-11e4-917d-2df0443b4c74.png)
````

Would produce this after it's automatically turned into Markdown and then rendered via GitHub:

![screen shot 2015-02-07 at 4 10 40 pm](https://cloud.githubusercontent.com/assets/896878/6094005/41b359c4-aee4-11e4-9942-c2c0b4f2e093.png)
