### ISSUE TITLE
allowing $ref in descriptions

### ISSUE THREAD

**Issue by manasesjesus** [OAI/OpenAPI-Specification#2697]
Some descriptions can be long or very long. Allowing $ref would be useful to reference an external file with only text, e.g. markdown. It'd be great if **info.description** and **tags.name/description** could use it (without IDE validation errors).

**Comment by webron** [comment]
How would you tell whether the description is a reference or actually the text itself?

**Comment by manasesjesus** [comment]
Specify it on a new line, like this:

```yml
openapi: 3.0.3
info:
  title: AcMe OpenAPI
  description:
    $ref: "markdown/acme-oas.md"

# more stuff here...

- name: Controls
  description:
    $ref: "markdown/controls.md"
```

It works like a charm; we render a web documentation and also `swagger-cli bundle` works fine, but the IDE shows error messages like this one: `Incorrect type. Expected "string". "yaml-schema: Validation schema for OpenAPI Specification 3.0.X."`

**Comment by webron** [comment]
It works like a charm if it's a JSON Schema document (which in many places its not). But what if those are the actual values of the description and are not meant to be references?

**Comment by hkosova** [comment]
@webron a literal string `$ref: "markdown/controls.md"` can be written as

```yaml
description: >-
  "$ref": "markdown/controls.md"

description: '"$ref": "markdown/controls.md"'   # note the extra quotes around the string

description:
  '"$ref": "markdown/controls.md"'   # note the extra quotes around the string

description: "\"$ref\": \"markdown/controls.md\""
```
or similar.

<br/>

This is different from
```yaml
description:
  $ref: "markdown/controls.md"
```
which denotes an object with the `$ref` key.
