### ISSUE TITLE
Support for nullable object

### ISSUE THREAD

**Issue by Poorva17** [OAI/OpenAPI-Specification#2733]
Hello team,

I am interested in marking `object` type as nullable.

Following did not work for me. Student is not shown as `nullable` in api spec.

```
components:
  schemas:
    Student:
      type: object
      nullable: true // does NOT work
      properties:
        name:
          type: string
          nullable: true // works
```
Am I missing anything here?
Note: name property is being shown as null or string but not student object.
