### ISSUE TITLE
Provide property to document "write once" on entity creation/immutability after creation for a field of an entity

### ISSUE THREAD

**Issue by Retro64** [OAI/OpenAPI-Specification#2743]
When creating an entity, sometimes initial values for a later readonly property might need to be created. Designing a schema with readonly does not work out, as it prevents writing once. Example:

```yaml
/entity/{id}
  get:
    schema:
      type: object
      properties:
        virtual:
          type: boolean
          readOnly: true
        name:
          type: string
         
  put:    
    schema:
      oneOf:
        - type: object
          description: use only on create
          properties:
            virtual:
              type: boolean
              writeOnly: true
            name:
              type: string
        - type: object
          description: use only on update (on name)
          properties:
            virtual:
              type: boolean
              readOnly: true         
            name:
              type: string
```

The schema looks kind of redundant, as `virtual` should only be set on first put and become immutable afterwards. It can currently only be "solved" by adding a description when to use which schema. Is there any way to design a schema, defining properties immutable after creation?
