### ISSUE TITLE
Declare an object and use its items in another object

### ISSUE THREAD

**Issue by emremrah** [OAI/OpenAPI-Specification#2825]
Consider I have a pair of keys and values that I use in most of my schemas. E.g.:
```yml
# ...
since:
  type: string
  example: "2019-01-01"
until:
  type: string
  example: "2019-01-31"
# ...
```

I would like to define this somewhere in the document and use it multiple times. E.g.:
```yml
# request body in application/json format
schema:
  type: object
  properties:
    property1: {}  # something
    property2: {}  # something
    "$ref": "#myObjects/sinceUntil/*"  # maybe like this? Beware that this shouldn't be an object itself; it should add since and until properties separately like in the first example
myObjects:
  sinceUntil:    
    since:
      type: string
      example: "2019-01-01"
    until:
      type: string
      example: "2019-01-31"
```

If there is a similar concept to do this, please let me know. Otherwise, this would be really good because I don't want to rewrite since and until properties everywhere. Thank you.

**Comment by karenetheridge** [comment]
```
components:
  schemas:
    since_and_until:
      type: object
      properties:
        since:
          ...
        until:
          ...
...
  somewhere else...
    schema:
      allOf:
      - $ref: /components/schemas/since_and_until
      type: object
      properties:
        other_property:
          ...
```
