### ISSUE TITLE
Feature Request: $ref for Operation Object 

### ISSUE THREAD

**Issue by fcasad** [OAI/OpenAPI-Specification#2922]
The current OAS 3.1 spec allows the use of $ref for "Path Item Object" but not for "Operation Object".  Is there a reason for this?  It would be quite nice to be able to break down a large doc at the operation level.  This could also be useful for describing APIs that are composed together (ie describing an API gateway).

**Comment by cebe** [comment]
If I understand your request correctly you could already do that, like this:

```yaml
paths:
 '/path1':
    get:
      '$ref': 'operations/path1-get.yaml'
    post:
      '$ref': 'operations/path1-post.yaml'

# ....
```
