### ISSUE TITLE
Inconsistency for accepted keys in Component fix fields

### ISSUE THREAD

**Issue by lasconic** [OAI/OpenAPI-Specification#2971]
In the 3.1 spec [one can read the following](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#fixed-fields)

```
All the fixed fields declared above are objects that MUST use keys 
that match the regular expression: ^[a-zA-Z0-9\.\-_]+$.
```

However, most of the fixed fields accept a Reference Object with the key $ref which doesn't match the regular expression.

This inconsistency or lack of precision causes some tools to enforce the regular expression blindly and do not consider $ref under parameters for example as a valid OpenAPI document. 
See for example : https://github.com/OpenAPITools/openapi-generator/issues/11151

**Comment by hkosova** [comment]
```yaml
components:
  schemas:
    SchemaName:    # <---- It's about these keys
      ...

  parameters:
    limit:         # <----
      ...
```

<br/>

The example from https://github.com/OpenAPITools/openapi-generator/issues/11151
```yaml
components:
  schemas:
    $ref: './definitions/_index.yaml'
```
is not valid OpenAPI syntax because `$ref` is not allowed directly under `components.<type>`, it's only allowed under `components.<type>.<name>`.
