### ISSUE TITLE
Standardize Parameter Models

### ISSUE THREAD

**Issue by dilipkrish** [OAI/OpenAPI-Specification#301]
It seems odd that ```Serializable``` parameters be treated differently that Body Parameters. In the interest of _consistency_, I would think that regardless of the type of parameter it should always have a **schema** property.

```yaml
"/api/pet/findByStatus": {
            "get": {
                ...
                "summary": "Finds Pets by status",
                "description": "Multiple status values can be provided with comma seperated strings",
                ...
                "parameters": [
                    {
                        "name": "status",
                        "in": "query",
                        "description": "Status values that need to be considered for filter",
                        "required": true,
                        "type": "string", //<-- NOTE: Seems like this should be standardized
                        "default": "available"
                    }
                ],
```
I would expect it to be rendered as shown below
```yaml
"/api/pet/findByStatus": {
            "get": {
                ...
                "summary": "Finds Pets by status",
                "description": "Multiple status values can be provided with comma seperated strings",
                ...
                "parameters": [
                    {
                        "name": "status",
                        "in": "query",
                        "description": "Status values that need to be considered for filter",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }, 
                        "default": "available"
                    }
                ],
```
