### ISSUE TITLE
[Doubt] How to refer a security scheme in a file where paths are defined

### ISSUE THREAD

**Issue by 123survesh** [OAI/OpenAPI-Specification#3092]
Currently, we are requested to defined the security schemes  globally and use them. This works well for the file that I defined the security scheme in. I am currently defining the paths of my API routes in separate files. Specific APIs have a different authentication API key than the ones globally set.

I tried this,
**main.yaml**
```yaml
components:
  securitySchemes:
    OrgAuth:
      type: apiKey
      in: header
      name: gktoken
    UserAuth:
      type: apiKey
      in: header
      name: gkusertoken
security:
  - OrgAuth: []
```

**path_orgs.yaml**
```yaml
post:
    summary: Create a new organisation
    security:
      - userAuth: []
```
![Screenshot from 2022-12-11 00-39-47](https://user-images.githubusercontent.com/8644987/206871511-8630793d-cf7b-4dcb-8c1e-face74691288.png)

I am facing no errors, but the auth details for the one defined in path_orgs.yaml is coming out empty. Does any one know how to solve this?
