### ISSUE TITLE
Proposal: Default options in discriminators

### ISSUE THREAD

**Issue by mattholden** [OAI/OpenAPI-Specification#3105]
I have the following use case I'd like to solve: 

```
type: object
description: Settings for a country
allOf:
   - type: object
      properties:
        country_code:
            type: string
            description: ISO 3166 country code
            enum: AD, AE, AF, AG .... ZW
        common_field:
            type: string
            description: Something all countries have
discriminator:
   description: Adds extra fields we need depending on country 
   propertyName: country_code
   mapping: 
       CA: #/CountryCA
       MX: #/CountryMX
       US: #/CountryGeneric
       DE: #/CountryGeneric
       ES: #/CountryGeneric
       # insert many more country definitions here that go to CountryGeneric
```

This can be made to work, but I would have to have all 200+ countries in the `mapping` object, each pointing to a reference of an object, and this is really cumbersome. I'd really love to be able to do this, treating the `discriminator` almost like a `switch` statement:

```
discriminator:
   description: Adds extra fields we need depending on country 
   propertyName: country_code
   mapping: 
       CA: #/CountryCA
       MX: #/CountryMX
   default: #/CountryGeneric
```
