### ISSUE TITLE
Group schema components by content-type

### ISSUE THREAD

**Issue by souenzzo** [OAI/OpenAPI-Specification#3168]
I'm working on an API that has many content-type, and they use references to schema

The references to the `user` entity, for example, aren't the same on each content-type.

I'm currently handling that by adding a content-type prefix on each schema:

```yaml
schemas:
  application/json_user:
    type: object
  application/custom+json_user:
    type: object
```

I'd like to use something like

```yaml
schemas:
  application/json:
    user:
      ...
  application/custom+json:
    user:
      ...
```

**Comment by MikeRalphson** [comment]
Is your desire to group the `schemas` for ease of editing, production of documentation or another use-case?

**Comment by souenzzo** [comment]
Because they are distinct and I don't want to pollute the name of the schema

For example, in my `application/custom+json` content-type, we wrap enums with objects like `{_t: enum, _v: "admin"}`

So we have 2 distinct `user` schemas, one for `application/json`, other for `application/custom+json`

```yaml
schemas:
  application/json_user:
    type: object
    properties:
      id:
        type: string
      role:
        type: string
        enum: [ admin, regular ]
  application/custom+json_user:
    type: object
    properties:
      id:
        type: string
      role:
        type: object
        properties:
          _t:
            type: string
            enum: [ enum ]
          _v:
            type: string
            enum: [ admin, regular ]
```

**Comment by karenetheridge** [comment]
You could use subschemas inside /components/schemas, via $defs:

```yaml
components:
  schemas:
    user:
      $defs:
        application/json:
          ..
        application/custom:
          ..
```

And then reference them as `"$ref": "#/components/schemas/user/$defs/application/json"`

**Comment by souenzzo** [comment]
@karenetheridge 

This indeed partially works, but `swagger-ui` does not support this kind of references

- Open https://petstore.swagger.io/#/default/get_
- paste this on swagger url
```
data:application/json;base64,eyJjb21wb25lbnRzIjp7InNjaGVtYXMiOnsidXNlciI6eyIkZGVmcyI6eyJhIjp7InR5cGUiOiJudW1iZXIifX19fX0sIm9wZW5hcGkiOiIzLjAuMyIsInBhdGhzIjp7Ii8iOnsiZ2V0Ijp7InJlc3BvbnNlcyI6eyJkZWZhdWx0Ijp7ImNvbnRlbnQiOnsiYXBwbGljYXRpb24vanNvbiI6eyJzY2hlbWEiOnsiJHJlZiI6IiMvY29tcG9uZW50cy9zY2hlbWFzL3VzZXIvJGRlZnMvYSJ9fX19fX19fX0=
```

<img width="462" alt="Screenshot 2023-02-22 at 07 09 50" src="https://user-images.githubusercontent.com/3241703/220589185-4641ec97-830e-4687-82fc-8384c2b3a1fe.png">


As we can see in the image

- The resolution of the schema works (we can find the `number` type in `GET /` route
- The bottom `Schemas` component does not support this kind of reference, showing an empty group

I would like to have an explicit example of this in OAI spec, then swagger-ui and other tools will be able to implement proper support.

**Comment by MikeRalphson** [comment]
> I would like to have an explicit example of this in OAI spec, then swagger-ui and other tools will be able to implement proper support.

@karenetheridge it would be great if you could PR a new example to the `examples/v3.1` directory 😁

**Comment by souenzzo** [comment]
@MikeRalphson I can do this PR?

**Comment by handrews** [comment]
Note that `$defs` is only allowed in OAS 3.1 and later, which Swagger UI does not support.

**Comment by souenzzo** [comment]
Something like this


```yaml

components:
  schemas:
    $defs:
      application/json:
        Error:
          type: object
          required:
            - code
            - message
          properties:
            code:
              type: integer
              format: int32
            message:
              type: string
      text/plain:
        Error:
          type: string

```

Can be added to [petstore](https://github.com/OAI/OpenAPI-Specification/blob/main/examples/v3.0/petstore.yaml#L103) example
