### ISSUE TITLE
Encoding Object examples have invalid schema property

### ISSUE THREAD

**Issue by jeremyfiel** [OAI/OpenAPI-Specification#3170]
Reviewing the [Encoding Object Examples](https://spec.openapis.org/oas/v3.0.3#special-considerations-for-multipart-content)

The keyword `type` should be `$ref`. 

```yaml
         addresses:
            # default Content-Type for arrays is based on the `inner` type (object shown, so `application/json` in this example)
            type: array
            items:
              type: '#/components/schemas/Address'
```
