### ISSUE TITLE
v3.1 - contentEncoding

### ISSUE THREAD

**Issue by commonism** [OAI/OpenAPI-Specification#3230]
The [example](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#special-considerations-for-multipart-content) from the spec:
```
          profileImage:
            # Content-Type for application-level encoded resource is `text/plain`
            type: string
            contentMediaType: image/png
            contentEncoding: base64
```            
contradicts the specification:
  * `If the property is a type: string with a contentEncoding, the default Content-Type is application/octet-stream`

[Henry Andreews agrees](https://stackoverflow.com/questions/67388636/in-a-json-schema-what-is-the-correct-way-to-describe-a-default-example-or-enu)
