### ISSUE TITLE
Feature request: standard file that describes what openapi features are supported by an implementation

### ISSUE THREAD

**Issue by spacether** [OAI/OpenAPI-Specification#3247]
Feature request: standard file that describes what openapi features are supported by an implementation

If all implementations provided a yaml or json file of what features were supported it would allow for easier comparison of implementations.

What if we did this with the json schema descriptions of the openapi spec:
https://github.com/OAI/OpenAPI-Specification/blob/main/schemas/v3.0/schema.yaml

And the json path was the feature, like:
`#/servers` and the value is a boolean or a FeatureSupportInfo object like so:

```
FeatureSupportInfo:
  type: object
  properties:
    supported:
      type: boolean
    docUrl:
      type: string
    verificationTestUrl:
      type: string
  required:
  - supported
```
