### ISSUE TITLE
Linked callback example appears to be non-conformant

### ISSUE THREAD

**Issue by handrews** [OAI/OpenAPI-Specification#3257]
Both the 3.0 and 3.1 specs have a link in the Callback Object patterned fields table to a "[complete example](https://github.com/OAI/OpenAPI-Specification/blob/main/examples/v3.0/callback-example.yaml)" which is a.) a 3.0.0 example for both versions, without it being immediately clear whether it's also valid for 3.1, and b.) uses an intermediate object level that does not appear to be allowed by the spec:

```YAML
      callbacks:
        # the name `onData` is a convenience locator
        onData:     ############# ERROR: This "convenience locator" level is not part of the spec AFACIT
          # when data is sent, it will be sent to the `callbackUrl` provided
          # when making the subscription PLUS the suffix `/data`
          '{$request.query.callbackUrl}/data':
            post:
```

3.0.3 specification text (3.1.0 is identical except for the internal link, plus it has a 2nd 1-line paragraph about webhooks):

> A map of possible out-of band callbacks related to the parent operation. Each value in the map is a [Path Item Object](https://spec.openapis.org/oas/v3.0.3#pathItemObject) that describes a set of requests that may be initiated by the API provider and the expected responses. The key value used to identify the path item object is an expression, evaluated at runtime, that identifies a URL to use for the callback operation.

The example probably needs to be corrected, if we even want to keep that link.  And probably duplicated to 3.1.
