### ISSUE TITLE
If then block from json schema to openapi yaml format

### ISSUE THREAD

**Issue by adryen31** [OAI/OpenAPI-Specification#3278]
I have the following json schema (which basically generated from a openapi.yaml file), I modified the json schema for some needs but I don't found the correct syntax for express the 'IF' block which allow to required 'Uuid' mandatory if is an 'action' of 'remove' type.

Anyone can help me for founding the good syntax in the yaml plz ? thank a lot and best regards.

bellow the json schema:

```
"Operation": {
    "type": "object",
    "required": [
      "action"
    ],
    "properties": {
      "action": {
        "description": "The server state",
        "type": "string",
        "enum": [
          "add",
          "remove",
          "modify"
        ]
      },
      "entity": {
        "description": "The entity",
        "type": "object"
      },
      "Uuid": {
        "description": "The uuid to remove",
        "type": "string"
      }
    },
            "if": {
                "properties": {
                    "action": {
                        "const": "remove"
                    }
                }
            },
            "then": {
                "required": ["Uuid"]
            }
  }
```

I tried this bellow, but without success pass the openapi swagger validation with the following error:

```
Operation:
  type: object
  required:
    - action
  properties:
    action:
      description: The server state
      type: string
      enum:
        - add
        - remove
        - modify
    entity:
      description: The entity
      type: object
    Uuid:
      description: The uuid to remove
      type: string
  if:
    properties:
      action:
        const: remove
  then:
    required:
      - Uuid
```

Structural error at components.schemas.BulkOperation should NOT have additional properties additionalProperty: if, then Jump to line 2592

Anyone else can help me plz ?
My main purpose is to declare the correction IF/THEN block in my YAML in order to correctly generate the json schema thank to https://editor.swagger.io/

cheers,
Adrien
