### ISSUE TITLE
Parameter schema specification via content 

### ISSUE THREAD

**Issue by commonism** [OAI/OpenAPI-Specification#3421]
I'd like to clarify the purpose of the [Parameter Object](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#parameter-object) schema specification depending on the media type via content.

> For more complex scenarios, the [content](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#parameterContent) property can define the media type and schema of the parameter.

What is this complex scenario?
Having different media types defined for the body, the parameters schema should depend on the media type of the body?

```yaml
  parameters:
    DefinedParameter:
      in: query
      name: value
      required: true
      style: form
      explode: false
      content:
        "application/json":
          schema:
            type: integer
            default: 5
          example: 5
        "multipart/form-data":
          schema:
            type: object
            $ref: "…"
```

If the [Media Type Object](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#media-type-object) encoding property is not to be used when used with Parameter Objects, so the encoding of possibly different parameter types is set by the parameter independent of the schema.
If the encoding is free be used for Parameter Objects… for an object this will combine different encodings for the objects properties?
