### ISSUE TITLE
Clarity on how to handle optional security

### ISSUE THREAD

**Issue by RobbeSneyders** [OAI/OpenAPI-Specification#3426]
We're wondering how to handle the following specification in [connexion](https://github.com/spec-first/connexion).

```yaml
security:
- api_key: []
- {}
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: X-Auth
      in: header
      x-apikeyInfoFunc: app.apikey_auth
```

If the user sends an invalid API key, should this request be accepted because security is optional, or rejected because the request is invalid according to the `api_key` security scheme?

When reading the specification to the letter, these schemes should be applied in an OR fashion, so the request should be accepted. However, from the user side, it probably makes more sense to alert them of the invalid API key and reject the request.

Related: https://github.com/OAI/OpenAPI-Specification/issues/1698
