### ISSUE TITLE
Clarification regarding the `allOf` composition when the given objects have a same property field

### ISSUE THREAD

**Issue by lnash94** [OAI/OpenAPI-Specification#3428]
Hi Team,

We are using the OpenAPI definition to generate [Ballerina](https://ballerina.io/) clients for integrations. In Ballerina, we have [record types](https://ballerina.io/learn/by-example/open-records/) that we directly map to OpenAPI object schemas. While I'm in the process of mapping the OpenAPI `allOf` concept, I've encountered a few concerns, and I would like to get your input to resolve my doubts. I'm using OpenAPI spec version 3.0.1

1. If the given allOf composed schema has multiple objects with the **same property field** with the **same type**, such as the `age` field being common to both inline objects, my question is: once we combine these, does it have one `age` property for the combined object, or is this a valid allOf scenario?

```yml
components:
  schemas:
    Cat:
      allOf:
        - type: object
          properties:
            name:
              type: string
            age:
              type: integer
        - type: object
          properties:
            hunts:
              type: boolean
            age:
              type: integer
```
2. If the given allOf composed schema has multiple objects with the **same property field** with the **different type**, such as the `id` field being common to both inline objects, my question is: once we combine these, does it have one `id` property with oneOf `string|integer`  for the combined object, or is this a valid allOf scenario?

```yml
components:
  schemas:
    Cat:
      allOf:
        - type: object
          properties:
            name:
              type: string
            id:
              type: integer
        - type: object
          properties:
            hunts:
              type: boolean
            id:
              type: string
```
3. If the given allOf composed schema has multiple objects with the **same property field** with the **different object reference type**, such as the `address` field being common to both inline objects, Is this a valid allOf scenario and what would be the combined output.

```yml
components:
  schemas:
    User:
      allOf:
        - type: object
          properties:
            name:
              type: string
            address:
              ref: "#/components/schemas/Address"
        - type: object
          properties:
            age:
              type: integer
            address:
              ref: "#/components/schemas/State"
    Address:
       type: object
       properties:
            home_no:
              type: string
           line_01:
             type: string
           city:
             type: string
   State:
        home_no:
           type: integer
         province:
           type: string
         city:
           type: string
```
Your thoughtful response would be greatly appreciated.
