### ISSUE TITLE
Separate annotation per enum value

### ISSUE THREAD

**Issue by cowwoc** [OAI/OpenAPI-Specification#348]
Following up on https://github.com/swagger-api/swagger-core/issues/1012 I'd like a service to return an Enum type and then document enum values by providing a separate annotation per value. I expect Swagger to aggregate these annotations so that all values and their descriptions are listed in the resulting documentation.

**Comment by bgrant0607** [comment]
+1. (Yes, github should have a voting button.)

**Comment by fehguy** [comment]
@cowwoc @bgrant0607 how would you propose this is represented in the description?  For example, the current enum system uses primitive arrays:

```yaml
myValue:
  properties:
    statusFields:
       type: string
       enum:
          - 1
          - 2
```

I suppose these could be objects, but we'll have to be prescriptive of the structure.

**Comment by cowwoc** [comment]
Each enum entry could be an object with `name` and `documentation` properties (or however you want to call it).

**Comment by henkosch** [comment]
+1

**Comment by jontejj** [comment]
@fehguy @cowwoc Or there could be a separate enumDescriptions array (keeping backwards compatibility) where the amount of descriptions should match the amount of enums. Perhaps it's not very pretty but it would be a way forward.

**Comment by drewish** [comment]
I would love to be able to use an object/hash for enums. For example I've got an app with credit card transactions that use rather cryptic values for the CVV checks. Here's what I'm forced to do to document it:
```yaml
cvv_check:
  type: string
  title: CVV check
  description: |
    When processed, result from checking the CVV/CVC value on the transaction.

    * `D` - Suspicious transaction
    * `I` - Failed data validation check
    * `M` - Match
    * `N` - No Match
    * `P` - Not Processed
    * `S` - Should have been present
    * `U` - Issuer unable to process request
    * `X` - Card does not support verification
  enum:
    - D
    - I
    - M
    - N
    - P
    - S
    - U
    - X
  maxLength: 1
```

It would be much nicer to just have:
```yaml
cvv_check:
  type: string
  title: CVV check
  description: When processed, result from checking the CVV/CVC value on the transaction.
  enum:
    D: Suspicious transaction
    I: Failed data validation check
    M: Match
    N: No Match
    P: Not Processed
    S: Should have been present
    U: Issuer unable to process request
    X: Card does not support verification
  maxLength: 1
```

Clients could either just use the keys and ignore the values, or show both in a `<select>` HTML element.

**Comment by ralfhandl** [comment]
+1

**Comment by webron** [comment]
I think there's a similar proposal for this for draft 5 of JSON Schema, will look for it.

**Comment by webron** [comment]
Parent issue: #579

**Comment by cabbonizio** [comment]
+1

**Comment by ePaul** [comment]
Currently the enum feature allows any kind of JSON thing in it – objects, arrays, strings, numbers, even mixed (though I'm not sure if things other than strings are supported by various toolings).

With the map variant proposed by @drewish we would be limited to strings. (This is not necessarily a problem for most cases, I just wanted to point it out.)

A more flexible version (though more verbose) would be to have an array of value/description pairs:

```yaml
cvv_check:
  type: string
  title: CVV check
  description: When processed, result from checking the CVV/CVC value on the transaction.
  enum:
    - value: D
     description: Suspicious transaction
    - value: I
      description: Failed data validation check
    - value: M:
      description: Match
    - value: N
      description: No Match
    - value: P
      description: Not Processed
    - value: S
      description: Should have been present
    - value: U
      description: Issuer unable to process request
    - value: X
      description: Card does not support verification
```

I guess this corresponds to what @cowwoc proposed.
