### ISSUE TITLE
Are Style Examples correct for arrays and objects

### ISSUE THREAD

**Issue by charjr** [OAI/OpenAPI-Specification#3481]
Referring to the [style examples section](https://github.com/OAI/OpenAPI-Specification/blob/3.1.0/versions/3.0.3.md#style-examples) _(identical on both 3.0.3 and 3.1.0)_:

I notice that some of the styles do not use the key "color" at all. For example:

[`style`](#dataTypeFormat) | `explode` | `empty` | `string` | `array` | `object`
----------- | ------ | -------- | -------- | -------- | -------
matrix | false | ;color | ;color=blue | ;color=blue,black,brown | ;color=R,100,G,200,B,150
matrix | true | ;color | ;color=blue | ;color=blue;color=black;color=brown | ;R=100;G=200;B=150

For `object` with `explode: true` the word `color` is not found within `;R=100;G=200;B=150`

Is this correct? If so, how does it maintain association with the object: `color`?

I may be wrong but I would expect something like this: `;color=R,100;color=G,200;color=B,150`.

Any enlightenment on this would be greatly appreciated. 
If it turns out there are any mistakes I'd be happy to put in a PR to update it.

**Comment by handrews** [comment]
@karenetheridge did one of your PRs fix this for the next patch release?

**Comment by karenetheridge** [comment]
The examples are correct. For those cases where "color" does not appear in the serialized form, the implication is that the parameter is meant to capture _all_ of the values, and its name is arbitrary because it does not appear in the serialized string.

Therefore, given this openapi parameter specification:

```yaml
name: color
in: query
explode: true
style: matrix
schema:
  type: object
```

..and this parameter string: `;R=100;G=200;B=150`, the deserialized data for `color` would be:

```json
{ "R": "100", "G": "200", "B": "150" }
```

and given this parameter string: `;foo=bar;bloop=yay;hello=goodbye`, the deserialized data for `color` would be:

```json
{ "foo": "bar", "bloop": "yay", "hello": "goodbye" }
```

This is also the solution for the sometimes-asked question "is there a way of capturing all query parameters into one openapi schema parameter [for example to describe dependencies between then]", e.g. asked here: https://github.com/OAI/OpenAPI-Specification/issues/256

**Comment by charjr** [comment]
@karenetheridge Thank you for the example, that is really helpful! 

I'm working on part of [a library](https://github.com/membrane-php/membrane-core) for validating requests against an OpenAPI. So I'm trying to work out all the weird, wonderful and horrible edge cases can be concocted in a query string.

I'm still unsure of what would happen for unusual edge cases such as two query parameters like this:

```yaml
parameters:
  - name: color
    in: query
    explode: true
    style: matrix
    schema:
      type: object
  - name: paint
    in: query
    explode: true
    style: matrix
    schema:
      type: object
```

Because now I'm imagining strings like this: `;R=100;G=200;B=150&type=watercolour;viscosity=0.1`.

Is that a correct example (i.e. could this actually happen)? If so, is there a set way to interpret that data or is it up to the tooling to decide?

**Comment by karenetheridge** [comment]
I _think_ that would be a parsing error, because of the presence of `&type=`, but I haven't yet added the matrix style to my implementation yet so I cannot test :)

**Comment by charjr** [comment]
That is where I'm at a loss: From my understanding, though rather nonsensical, this is technically valid:

```yaml
parameters:
  - name: color
    in: query
    explode: true
    style: matrix
    schema:
      type: object
  - name: paint
    in: query
    explode: true
    style: matrix
    schema:
      type: object
```

But I do not know how one would form a valid query string for it, **especially** if I were to specify `required: true` on both.

Can anyone specify what a valid query string would look like in this instance?
