### ISSUE TITLE
Clarification regarding a schema containing both `oneOf` and `required` types

### ISSUE THREAD

**Issue by dilanSachi** [OAI/OpenAPI-Specification#3618]
I have a schema definition as follows.

```
    RenderRequest:
      oneOf:
        - required:
            - url
        - required:
            - html
      properties:
        block_ads:
          type: boolean
        click_accept:
          type: boolean
        html:
          type: string
        thumb_width:
          type: integer
        url:
          description: The URL to render as an image or video
          type: string
      type: object
```

I need to understand what is meant by here. First of all, is this a valid schema definition? If so, does this mean that in the `RenderRequest`, one of `url` or `html` is mandatory?
