### ISSUE TITLE
Is it possible to name an object property default?

### ISSUE THREAD

**Issue by sydneyhenrard** [OAI/OpenAPI-Specification#4101]
I have the following definition:
```
type: object
properties:
  type:
    type: string
  references:
    type: array
    items:
      type: object
      properties:
        reference:
          type: string
        axis:
          type: object
  default:
    type: string
```
I got these errors from the spectral linter, so I wonder if the issue is coming from the fact that the attribute is named **default**.
```
 error  oas3-valid-schema-example  schema is invalid: data/type must be equal to one of the allowed values, data/type must be array, data/type must match a schema in anyOf
 error  oas3-valid-schema-example  type must be JSONType or JSONType[]: [object Object]
```
I have no issue when generating code with this definition.
