### ISSUE TITLE
Is it possible to indicate the requiredness of a `multipart/form-data`'s request's `filename` directive?

### ISSUE THREAD

**Issue by TomerAberbach** [OAI/OpenAPI-Specification#4442]
As far as I can tell, the `required` property in the OpenAPI spec can be used to specify that an entire `multipart/form-data` part is required, but it cannot be used to indicate whether the [`filename` directive](https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Content-Disposition#filename) is required.

This would be pretty useful since some `multipart/form-data` endpoints require the `filename` directive while others do not. If OpenAPI allowed specifying those semantics, then that could be used in various generators that consume OpenAPI (e.g. an SDK generator could check whether the end-user supplied a `filename` if it's required).

**Comment by TomerAberbach** [comment]
Thanks for confirming! 

Is there anything I can do to help with getting it into the spec?

**Comment by TomerAberbach** [comment]
Cool, that makes sense! 

I'm happy to get involved here if you think it'd be helpful, but if you already have a handle on this revamp, then I'll leave it to you :)

**Comment by handrews** [comment]
@TomerAberbach we probably won't get to it until the summer, as we need to get 3.2 out the door (or at least mostly finished) first.

**Comment by TomerAberbach** [comment]
Noted. Let me know if you need any more info from me when the time comes

**Comment by baywet** [comment]
Kind of related to #2458 and #2342

**Comment by karenetheridge** [comment]
> as of today there is no way no manipulate the content disposition

You can do it today with a regex on the header string:

```
...
content:
  multipart/form-data:
    encoding:
      foo:
        headers:
          Content-Disposition:
            schema:
              type: string
              pattern: '^form-data\s*;\s*filename\*?\s*='
```
