### ISSUE TITLE
Is it possible to reference query parameter to enum defined in `definitions` ?

### ISSUE THREAD

**Issue by cppexpert** [OAI/OpenAPI-Specification#564]
Is it possible to reference query parameter to enum defined in `definitions` ? For example consider following example:

```yaml
paths:
  /users/test:
    get:
      summary: Test endpoint
      parameters:
        - name: osType
          in: query
          description: Client's OS type.
          required: true
          type: string
          enum:
          - ios
          - android
```

then I define this

```yaml
definitions:
  OsTypes:
    type: string
    enum:
    - ios
    - android
```

Can I reference it from endpoint to avoid defining allowed values of the enum in every endpoint that uses it ?

I tried 

```yaml
schema:
  $ref: '#/definitions/OsTypes'
```

Thanks!
