### ISSUE TITLE
Allow documenting HATEOAS APIs (pathless operation / interface / URI class / operation type)

### ISSUE THREAD

**Issue by ePaul** [OAI/OpenAPI-Specification#577]
## TLDR

_(added after some discussion)_
- "interfaces" (like path items, just without path parameters, and not linked to a path template)
- a path item can refer to an interface (which is implemented), possibly adding path parameters to it
- a string property (containing an URI) in a schema can refer to an interface (which means the consumer can know which operations can be used on this URI)
## Background / Current Situation

I work at a company where our [Restful API Guidelines](http://zalando.github.io/restful-api-guidelines/index.html) prescribe both ["document your API using OpenAPI"](http://zalando.github.io/restful-api-guidelines/general-guidelines/GeneralGuidelines.html) and ["Use HATEOAS"](http://zalando.github.io/restful-api-guidelines/hyper-media/Hypermedia.html) ("Hypertext as the Engine of Application State", one of the core principles of REST).

Unfortunately both do not work together nicely:
- Swagger/OpenAPI 2.0's model is "we have paths which can be distinguished in some way, and describe the operations on those paths" (including their data format).
- The HATEOAS model is "The client gets a result which might contain links to other resources, and can decide to follow them, no matter which URI format they have".

Currently the intersection between both is "have links in your result, but just to URIs which are also described as paths in your Swagger definition, and describe in descriptions what kind of URIs you can expect".
## Ideas

A core point of HATEOAS are media types and link relations. An API definition should mainly be a description of the media types and what operations they imply for links included in them. (Paraphrased from a [blogpost of Roy Fielding](http://roy.gbiv.com/untangled/2008/rest-apis-must-be-hypertext-driven).)

Media type definitions are analogous to what OpenAPI's `definitions` are currently, might even be an extension of that. For models with a property of type `string`, format `uri` we can then additionally refer to the _URI class_ of that URI.

A **URI class** is defined analogously to the current path definitions, but with some name to be used in model definitions. The URI class defines what operations are possible on an URI, which parameters are allowed/needed (no path parameters, I guess), and what can be expected in return. (The URI class is not a property of the URI itself, but of its usage in a specific place. The same URI could appear with multiple URI classes.)

_I'm not yet sure how link relations can come into this – I guess we might need a way to define the URI class depending on link relation or similar._

A client needs just some initial "bookmark URI" (so a single path definition might be fine), and then can take a link (with a given URI class) and use the operation behind the URI class to do what it wants to do. The format of the second URI doesn't matter anymore to the client – it can even have a different domain name than the bookmark one. But still everything can be strongly typed if wanted.

**Comment by ePaul** [comment]
I guess this is a bit related to #576 (that discussion caused me to write this now down, though I had the ideas in me for a while), but this is much wider in scope.

**Comment by mpnally** [comment]
See my comments on  #576 for one possible approach to this.

**Comment by ePaul** [comment]
@mpnally's [comment](https://github.com/OAI/OpenAPI-Specification/issues/576#issuecomment-187504114) on #576 gives some ideas on how this could be done, thanks.
I would prefer not to use YAML-specific features and stay within what can be expressed in JSON, too.

I can imagine something like this (modified from the linked comment):

```yaml
uri-classes:
   Widget:
      get:
        ...
      put:
        ...
paths:
   /widget/{widget_id}:
      parameters:
         - name: widget_id
           in: path
           ...
      uri-class: Widget

definitions:
  Doohickey:
    properties:
      widget:
        description: hyperlink to a Widget
        format: uri
        type: string
        uri-class:
          $ref: '#/uri-classes/Widget'
```

(The path definition here isn't even needed if clients don't have to know the widget_id, and can reach that kind of uri from somewhere else. It might be needed for implementation help on the server side, but is not needed in the interface to be used by the client.)

I'm not sure if `interface` (or `x-interface`) is a good name for this "kind of resource to be find behind a URI", which I called "URI class", missing a better term.

**Comment by mpnally** [comment]
Terminology aside, your use of $ref is better than using the YAML merge operator (<<). I used YAML merge because I needed a solution that was legal today in swagger 2.0 and so would work with existing tools.

**Comment by fehguy** [comment]
Parent issue #560

**Comment by DavidBiesack** [comment]
The use of x-interfaces / x-interface in #576 seems to solve a different problem (that of several APIs or API subresources implementing an API contract/interface/pattern.)

I'm more interested in the OP question of defining and documenting an API via HATEOAS. We'd like to **hide** the paths in the API (i.e. in the UI) and encourage clients to consume **links** rather that hard-code the API to fixed paths. (The paths become more of an implementation detail. They still exist and could be revealed in the UI for reference / lookup, or presented in an alternate view.)

Thus, an API starts at the root and the client can discover the set of links to nested *resources* via compound keys that include a link relation (name), a verb (PUT, POST, etc.), a type (request and/or response media type), and a description. The definition of a link may also include a path but that is more of an implementation attribute. Thus, each path in an OAS can be associated with one or more contained *resources*

For example if the API has two primary resources, `models` and `activities`, the root 
would contain

```
paths:
  /:
    resources:
      root:
        links:
          models: 
               rel: models
               method: GET
               uri: /models
               type: application/vnd.collection+json
               description: Retrieve a paginated list of models
          createModel:
               method: POST
               uri: /models
               type: application/vnd.example.model+json
               description: Create a new model resource in this collection
          activities: 
               method: GET
               uri: /activities
               type: application/vnd.collection+json
               description: Retrieve a paginated list of activities
          createActivity:
               method: POST
               uri: /models
               type: application/vnd.example.activity+json
               description: Create a new activity resource in this collection


  /models:
    resources:
      models:
        collectionItems:
          model:
             uri: /models/{modelId}
        links:      # these are links associated with the collection
          self:
            ...
          next:
            ...
          prev:
            ...
          first:
            ...
          last:
            ...
          create:
            ...
  /models/{modelId}:
    resources:
      model:
        links:
          self:
            method: GET
            type: application/vnd.example.model+json
            description: Fetch a representation of this model
          image:
            method: GET
            type: image/png
            description: Fetch a graphical representation of this model
          pdf:
            method: GET
            type: application/pdf
            description: Fetch a PDF representation of this model
          update:
            method: PUT
            type: application/vnd.example.model+json
            description: Replace the representation of this mdoel
          patch:
            method: PATCH
            type: application/vnd.example.model+json
            description: Update the representation of this mdoel with partial representation
          delete:
            method: DELETE
            description: Delete this model.
          analyze:
            method: POST
            type: application/vnd.example.activities+json
            uri: /activities?model={modelId}
            description: Create an analysis activity
```

So from the root, one can find models and activities (as resources), and also discover how to create activities, and from the collection, one can access an individual model. From a model, there are links for operations on that model (the uri is inherited from the current path context).


The UI could then navigate the API by exploring links (hiding the URI by default).
