### ISSUE TITLE
Hasmaps payloads

### ISSUE THREAD

**Issue by gedaiu** [OAI/OpenAPI-Specification#593]
parent issue #579

I would be nice to be able to define hashmaps payloads.

I have an use case in an app, where I want to send a list of variables, defined by user. With the 2.0 spec, there is no way of defining a schema object that can contains any key like a Json object...

**Comment by ePaul** [comment]
I guess one reason for this is that [JSON](http://www.json.org/) allows only String keys in key-value pairs in a object.

A possible workaround would be to use an array with "pair" objects, which works already now:

```yaml
definitions:
  my_hashmap:
    type: array
    items:
      type: object
      properties:
        key:
          # your key type, for example
         type: object
         properties:
            name: string
       value:
          # your value type, for example
         type: object
         properties:
           example: integer
```

A value of this type could look like this:
```json
[ {"key": { "name": "Paul" }, "value": { "example": 42 } },
  {"key": { "name": "gedaiu" }, "value": { "example": 17 } } ]
```

**Comment by DavidBiesack** [comment]
1+; we have several cases where we want to allow an arbitrary attributes object of name/value pairs. We're happy with just string keys but desire values being scalars, arrays or nested maps.

**Comment by webron** [comment]
Isn't that supported by `additionalProperties`?

@gedaiu @DavidBiesack can you provide a sample of such payload? Not a schema of it, just what you want to payload to be.

**Comment by gedaiu** [comment]
@webron yes, here it is my case:

```
{
   "id": "0",
   "name": "process1",
   "variables": {
       "seconds": 3600,
       "hours": 30 
   }
}```

where `variables` is my hash map

**Comment by webron** [comment]
Are any properties in that payload arbitrary? If not, there's no problem describing that with the current version of the spec.

**Comment by gedaiu** [comment]
@webron sorry... maybe my comment was not that clear... the `variables` object can have any property. I don't know how to give a better example...

**Comment by webron** [comment]
@gedaiu then you just define variables as this:

```yaml
variables:
  type: object
  additionalProperties: {}
```

If you want to limit the type of the variables, say to integers:
```yaml
variables:
  type: object
  additionalProperties:
    type: integer
```

This is supported by the current version of the spec.
