### ISSUE TITLE
Add support for different execution environment, e.g. sandbox

### ISSUE THREAD

**Issue by IvanGoncharov** [OAI/OpenAPI-Specification#641]
Many APIs have multiple environments for execution of the same calls.
Examples are sandbox, geographical locations(to minimise latency), different instances of the same service, etc.

Currently, it impossible to describe multiple environments in the same document but @fehguy proposal from #640 to add array of hosts to spec:
```yaml
 hosts:
   - scheme: http
     host: foo.com
     port: 8080
     basePath: /bar
   - scheme: https
     host: foo.com
     port: 8443
     basePath: /baz
 ```
It seems like good solution for this problem, but it missing few essential details:
 * `title` field
 * `description` field
 * some mechanism to mark default host
