### ISSUE TITLE
Allow multi-dimensional arrays as query parameters

### ISSUE THREAD

**Issue by nsossonko** [OAI/OpenAPI-Specification#682]
Essentially, objects should be allowed at the query parameter level because it is perfectly legal to have a multi-dimensional array in a query parameter. Eg:

?q[first][]=First&q[last][]=Last

The spec already supports arrays with no keys, but not this format.

Thanks.

**Comment by ePaul** [comment]
Do you have a proposal on how this could look in an API definition? Do you want to allow arbitrary keys (to be chosen by the caller), just keys which are predefined in the API definition, or both?

**Comment by starfishmod** [comment]
I would think this is like being able to use complex (or object based) parameters. This output is what you see generally in jquery and what PHP uses (I am assuming others do as well). 
I can here looking for a solution as well to describe an API that uses calls with object based variables.

could this look like:
```
parameters:
  q:
    type:'object'
    in: query
    properties:
       firstname:
         type: array
         items:
           type: string
```
