### ISSUE TITLE
Add support for patternProperties in schemas

### ISSUE THREAD

**Issue by dolmen** [OAI/OpenAPI-Specification#687]
JSON Schema draft 4 has [`patternProperties`](http://json-schema.org/latest/json-schema-validation.html#anchor64) which is not supported by Swagger 2.0.
patternProperties allows to have loosely defined objects where the list of keys is not fixed in the spec (like `additionalProperties` allows in Swagger 2.0), but the format of the keys is restricted with a regexp (contrary to `additionalProperties` where keys are not at all limited).

Here is a use case from #380:

``` yaml
name: pop
description: population by country
type: object
patternProperties:
  '^[A-Z]{2}$':
    type: integer
    description: the population of the country indicated by the property name.
```

**Comment by ePaul** [comment]
It also allows having several patterns with each a different value schema:

```yaml
type: object
patternProperties:
  '^[A-Z]{2}$':
    type: integer
    description: the population of the country indicated by the property name.
  '^[A-Z]{3}$':
    type: string
    description: the name of the airport with the given IATA airport code.
```

I suppose this was deemed as too complicated to map to statically typed programming languages when choosing which features from JSON schema to use in Swagger 2.0. (I still can not imagine how a schema like this would be mapped to a Java class.)

**Comment by webron** [comment]
Related to #333.
Parent: #586

**Comment by webron** [comment]
Tackling PR: #741

**Comment by sukrit007** [comment]
👍

**Comment by daicoden** [comment]
For java, if you add another key `name` to each pattern property, you could generate an API

```yaml
type: object
patternProperties:
  '^[A-Z]{2}$':
    type: integer
    name: population
    description: the population of the country indicated by the property name.
  '^[A-Z]{3}$':
    type: string
    name: airports
    description: the name of the airport with the given IATA airport code.
```

```java
request.getPatternProperty("population") <- Map<String, Integer>
request.getPropertyPattern("airports").put("DEN", "Denver International Airport")
```
