### ISSUE TITLE
Structural improvements: enhance headers handling

### ISSUE THREAD

**Issue by arno-di-loreto** [OAI/OpenAPI-Specification#690]
Following (again) ideas from #563 and #684, extending #369:

- define reusable response headers (like parameters or definitions as proposed in #563 by @fehguy )
- set responses headers on each level: whole api, path, operation, responses (and response as stated in #369)

```YAML
paths:
  responseHeaders:
     # Headers returned on all api responses
  /resources:
    responseHeaders:
      # Headers returned on all /resources operations responses
    get:
      responseHeaders:
        # Headers returned on all operations responses
      200:
         headers:
           # Headers returned on this response
schemas:
  responseHeaders:
    # reusable headers describe with a Header Object, used with $ref
```

The problem is the naming consistency: `responseHeaders` almost everywhere vs `headers` on response level.
What if we use `headers` or `responseHeaders` everywhere?

nb: and don't forget to modify Header Object to include #321 (required)
