### ISSUE TITLE
Field Deprecation in Schema Objects

### ISSUE THREAD

**Issue by jayadeba** [OAI/OpenAPI-Specification#701]
Hello, I was browsing through the spec docs to find out how to mark deprecation at various levels for an API. I could find docs/prs specifying how to mark deprecation of an operation and deprecation of a parameter (query, header  or an entire Schema Object) but its not clear how can we mark a field in a Schema Object deprecated? Is there a plan to add support for this?

Appreciate any clarification around this.

Thanks,
Jayadeba Jena

**Comment by ePaul** [comment]
In the current version 2.0 there is nothing directly in the spec, so you'll have to write it into the description.
For the next version, #524 + #637 added it.

**Comment by jayadeba** [comment]
@ePaul Thanks for the answer. I browsed through the above but i find only the following:

1. You deprecate an operation (operation object).
2. You can deprecate a parameter (parameter object level).
3. You deprecate a model/schema, which deprecates all the fields of a schema/model.

For 3, how do i deprecate just one field in the schema?

Thanks

**Comment by ePaul** [comment]
The problem is that a field in a schema doesn't have any location where data could be added, other than the field's schema. So you'll need to put it there:

```yaml
definititions:
  Person:
    type: object
    properties:
      name:
        type: string
      age:
        type: integer
        deprecated: true
        description: The age of the person in years. This property is deprecated because you shouldn't care about someone's age.
```

Of course, this gets ugly when you are using $ref and one of the properties referring a schema is deprecated and another one not – you need to duplicate.

Maybe a better way to do this would be a list of deprecated properties in a schema, just like `required`.
