### ISSUE TITLE
Different representation of the enum in the model object

### ISSUE THREAD

**Issue by Sulbigar** [OAI/OpenAPI-Specification#727]
Hi,

I have a use case where the request and the response model definitions look exactly the same.
However, there is one field in the object which returns more enum values during the get operation but restricts to minimal enum values for the put operation. Is it possible to reference different enum values for the same field. I do not want to recreate the entire mode definitions for request and response for this sake.

Here is my example,

```
definitions:
  EntryRequest:
    properties: 
      entries:
        $ref: '#/definitions/EntityResponse/properties/entries'
  EntryResponse:
    properties:
      entries:
        type: array
        items:
          $ref: '#/definitions/Entry'
  Entry:
    properties:
      entryStatus:
        type: string
        enum:
          - ENABLE
          - DISABLE
          - IN_PROGRESS
```

In the above, there are two things that I'm worried about.
1) For EntryRequest, the API accepts only ENABLE/DISABLE for PUT operation while the API returns all of them in the GET operation. I would like to create a reference to the entryStatus property conditionally. Is it possible?
2) Also, everything except the entryStatus is same for both the EntryRequest and EntryResponse object model. I do not want to duplicate that as well for the sake of representing the differentiating the differences of entryStatus field.

Is there a way to do it?

**Comment by Sulbigar** [comment]
As I learn more on this, I get a feeling that this is more an yaml related query. But I would like to have it here to see if anyone has faced a similar situation and how they have handled it. Or to see if I get any recommendations on how to handle this.
For tagging different enums to the same field, I think I can do like this,

```
RequestEntryStatus:
  type: string
  enum: &requestStatus
    - ENABLE
    - DISABLE

ResponseEntryStatus:
  type: string
  enum:  &responseStatus
    - ENABLE
    - DISABLE
    - IN_PROGRESS

Entry:
  properties:
    entryStatus: *requestStatus
```

But still this would enforce me to create duplicates of request and response objects with different mapping to the entryStatus field. I would like to know if there is a better way to handle this.
