### ISSUE TITLE
Example for parameters

### ISSUE THREAD

**Issue by nemenemsrouge** [OAI/OpenAPI-Specification#743]
Hello,

Why it is not possible to define example for parameters?

I would like to have something like that

```yaml
- name: "external_id"
  in: "query"
  description: "Filter the result set by **external_id**"
  required: false
  type: "string"
  example: "123-456#789:0.2"
```

but swagger editor says : 

> Not a valid parameter definition

I just don't understand why it is not included into standards specs
