### ISSUE TITLE
Parameters Object does not list `examples` field

### ISSUE THREAD

**Issue by DavidBiesack** [OAI/OpenAPI-Specification#766]
I looked at #636 again after @darrelmiller posted "Extending representations to parameters and headers" #762 . I think the **[Parameter Object](https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.md#parameterObject)** section should include the (singular) `example` field under **[Fixed Fields](https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.md#fixed-fields-9)**.  `examples` are used in parameters in the samples under **[Examples Object](https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.md#examplesObject)** :

```
# in a parameter

  parameters:
    - name: 'zip'
      in: 'query'
      type: 'string'
      format: 'zip'
      example: 
        $ref: 'http://foo.bar#/examples/zip-example'
```

Also, given the ongoing discussions about multiple representations/content in #762 the `example` or `examples` field should be added to  `content` (was `representations`) content object, as examples and `content` objects should apply to parameters as well.
