### ISSUE TITLE
passing a 2D array from python to swagger

### ISSUE THREAD

**Issue by eehsan** [OAI/OpenAPI-Specification#772]
I have a python code that returns [["BLAH"],["BLAH"]]. The swagger.yaml segment that handles the output of this python code is:

```
results:
    type: "object"
    required:
    - "content"
    properties:
      content:
        type: "array"
        items:
          type: "array"
          items:
            type: "string"
```

but it doesn't work and gives the following error:

>   .... for x in self.response)
>   File "/usr/local/lib/python3.4/dist-packages/werkzeug/_compat.py", line 190, in to_bytes
>     raise TypeError('Expected bytes')
> TypeError: Expected bytes
> 

Using the same code and the same swagger.yaml, it works as expected when the return array from the python code is not nested: ["BLAH", "BLAH"]

It seems that it doesn't recognize the nested array case. while the swagger.yaml file obviously defines the output type as a nested array of strings. Note that I am using swagger 2.0.
