### ISSUE TITLE
Experiments with templated hosts

### ISSUE THREAD

**Issue by darrelmiller** [OAI/OpenAPI-Specification#779]
On the TDC call today, we experimented with a few different options for enabling parameterized host, schema and basePath.  Community feedback would be much appreciated.

Option 1: Global parameters are back

``` json

{
    "openapi" : "3.0.0",

    "parameters" : {
        "version" : {
            "in" : "basepath",
            "default" : "v1.0", 
            "schema" : {
                "type" : "string"
            }
        },

        "environment" : {
            "in" : "host",
            "required" : true, 
            "schema" : {
                "type" : "string"
            }
        }
    },

    "hosts" : [
        { 
          "host" : "{environment}.example.org",
          "basePath" : "/{version}/api",
           "scheme" : "https"
         }
    ]

}
```

This is a minimally intrusive option but it brings the `parameters` back at the global scope which we are not particularly keen to do.

The next option trades the current array of `hosts` into a `server` object so that it can contain the `host` related parameters.  It also means that there is only one baseUrl, but it can be parameterized and in fact the entire thing could be a parameter, which could allow for multiple static values using an enum parameter.

``` json
{
    "openapi" : "3.0.0",

    "server" : {
       "baseUrl" : "{scheme}://{environment}.example.org/{version}/api",

        "parameters" : [
             {
                "name" : "scheme", 
                "in" : "host",
                "default" : "https", 
                "schema" : {
                    "type" : "string"
                }
            },
             {
                "name" : "version", 
                "in" : "host",
                "required" : false, 
                "default" : "v1.0", 
                "schema" : {
                    "type" : "string"
                }
            },

            {
                "name" : "environment",
                "in" : "host",
                "required" : true, 
                "schema" : {
                    "type" : "string"
                }
            }

        ]
    }

}

```

There are concerns about how `default` values work in these parameters and the `"in" : "host"` is redundant but there just for consistency with the parameter object definition.

**Comment by ePaul** [comment]
Hmm, the `in: host` parameter would work for a operation-specific parameter just as well, I think. No need for global parameters here.

**Comment by darrelmiller** [comment]
@ePaul I suppose it would.  Do we really want to have to specify the parameter in every operation though? Even if we $ref it, it is still a pain.

**Comment by ePaul** [comment]
Hmm, good point. But didn't we have global (or at least path-level) parameters too?

**Comment by darrelmiller** [comment]
Open 3.0 does have path item parameters, which is a bit less redundant than operation parameters, but still a little annoying.  How do you feel about defining a parameters object inside a hosts/server object?

**Comment by DavidBiesack** [comment]
In option 2, should `"in" : "host"`, be `"in" : "baseUrl"` ? I think the name `host` is misleading here.

Also, I think the "server" element name is also a bit misleading since it is a URL not just a server. I suggest using `"baseUrl"` for the outer container (a natural progression from `"basePath"` in 2.0) and it have `"value"` and `"parameters"` members:
```
{
    "openapi" : "3.0.0",
    "baseUrl" : {
       "value" : "{scheme}://{environment}.example.org/{version}/api",
        "parameters" : [ ... ]
}
```

**Comment by DavidBiesack** [comment]
Is there some additional background material on this proposal -what is the motivation/use case and what is the problem this solves? For example, how are the default values overridden? Can I open an Open API spec in the UI and set `baseUrl` parameters when I want to 'Try it out' ? 

I suggest considering  _profiles_ , where a profile is a collection of parameter names/values. associated with values for these parameters (i.e. version 1.0, version 1.1, version 2.0) or for example dev/test/prod profiles to referencing the same API on dev, test, and prod servers. A specific profile may need to set more than just one variable such as `environment`; it may want to set `{port}` and `{version}` or some other `baseUrl` path parameter.

**Comment by darrelmiller** [comment]
@David  Yes, using in:host is misleading, however, it was a continuation of the current state of OpenApi 3.0 where "hosts" is a top level element that contains "hosts", "basePath" and "scheme".
'server' was an attempt to fix that, but I agree it's not ideal.  Hoisting `baseUrl' to the root is an interesting alternative that is pretty clear.

The issues we are trying to address are mainly those brought up in issue #169.  If I were to try and distill the intent to a single sentence, I would say: That by allowing parameters in the baseUrl we can use a single OpenAPI specification to access multiple implementations of the HTTP interface it describes.

The idea of parameter `profiles` is an interesting idea.  I need to think about that some more.

**Comment by fehguy** [comment]
@darrelmiller I've thought through this, here is my take.

* I'm guess host parameterization will be something that will not be used by a majority of users.  We shouldn't complicate the baseline case for the parameterization
* Parameters will always be strings
* The location will always be in the URL
* There is no value in reusing them throughout the specification

With that, I'm suggesting we not try to reuse the `parameter` object, as it is never interchangeable with host parameters.  We should create a new type, with the following properties:

* `type: string` is implied
* `required: true` is implied
* `default` is required
* `enum` is optional

That would produce something like this:

```yaml
server:
  url: {scheme}://{environment}.gigantic-server.com/{base}
  templateParameters:  # <== let's choose a different name?
    scheme:
      enum:
      - http
      - https
      default: https
    environment: # no enum, so accept anything
      default: development
    base:
      enum:
      - /v1
      - /v2
      default: /v2
```

This ends up being nice an concise.  In the degenerate case:

```yaml
server:
  url: http://petstore.gigantic-server.com/v2
```

**Comment by jharmn** [comment]
+1 to @fehguy's assertion that the `parameter` object is not a great fit here.

The problem being solved here is that any given environment should be able to change the server URL. As such, environment should be a top-level key with template params under it.
Then, environment specific URLs could be automagically built without any guessing.

Refining @fehguy 's example, with what I think is more realistic usage:
``` yaml
server: 
  url: "{scheme}://{host}:{port}/{base}"
  defaultTemplate: development
  templates:  // effectively 'environments' in practice 
    development: 
      scheme: 
        default: http
      host: 
        default: development.gigantic-server.com
      port:
        enum:
          - 8080
          - 8088
        default: 8080
      base: 
        default: v2
    production: 
      scheme: 
        default: http
        enum: 
          - http
          - https
      host: 
        default: api.gigantic-server.com
      port:
        default: 80
      base: 
        default: v2
        enum: 
          - v1
          - v2
```

Default (aka degenerate) case:

``` yaml
server:
  url: http://development.gigantic-server.com:8080/v2
```
