### ISSUE TITLE
defined fixed header

### ISSUE THREAD

**Issue by MartijnR** [OAI/OpenAPI-Specification#789]
The API I'm defining requires a custom header with a fixed value to be sent. Is there a way to define this using the OpenAPI specification?

The closest I got was this

```yaml
      parameters:
        - name: X-MyApp-Version
          in: header
          description: Fixed X-MyApp-Version header.
          type: string
          default: "1.0"
```

But this just provides a default when the value should be fixed to 

```
X-MyApp-Version: 1.0
```
