### ISSUE TITLE
Add option to require all fields in an object definition.

### ISSUE THREAD

**Issue by Stargateur** [OAI/OpenAPI-Specification#826]
There is a way to require all fields in an object definition ? Like this, for example.
``` yaml
required: true
properties:
  foo:
    type: string
  bar:
    type: string
```

It could be very nice to use.
