### ISSUE TITLE
Why required of object definition are not with properties field ?

### ISSUE THREAD

**Issue by Stargateur** [OAI/OpenAPI-Specification#827]
It's strange that required field in definition object are not directly to properties field.
``` yaml
required:
  - foo
properties:
  foo:
    type: string
```
This will be more easy to use ?
``` yaml

properties:
  foo:
    type: string
    required: true
```
And they are no warning or error if you add a wrong name in required.
