### ISSUE TITLE
Extend External Documentation Object to allow x- extensions

### ISSUE THREAD

**Issue by DavidBiesack** [OAI/OpenAPI-Specification#844]
The schema for [External Documentation Object](https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.md#external-documentation-object) is fixed and allows only `description` and `url`. 

I propose allowing `x-` extensions here so that vendors can add additional metadata about such doc.

This example shows how we might allow doc to be embedded directly in the UI rendering of the API. 
```YAML
  description: 'Details ...'
  url: './operation-xyz-details.md'
  x-embed: true
  x-format: markdown
```
This is very useful for reusable documentation. Documentation for operations and schemas in particular would benefit from having additional documentation which is tedious to embed directly in the OAS document as YAML or JSON. 

I'm not suggesting that `x-embed` be part of the spec, just that it makes sense to be able to add additional details about an external doc.
