### ISSUE TITLE
Possible to use $ref in security and securityDefinitions?

### ISSUE THREAD

**Issue by atdiff** [OAI/OpenAPI-Specification#846]
For large API structures, it makes sense to have API and definitions split out into multiple files for reuse and readability. Both security and securityDefinitions seem like properties that would benefit from leveraging the use of $ref. This way security info can be shared across multiple swagger files for one application.
Is it currently possible and are there examples of how to do it? I've tried multiple ways of defining the structure and nothing seems to work/get validated.

**Comment by radj** [comment]
This is especially applicable when the scopes are the same in many path+operation permutations.

**Comment by dosvath** [comment]
If it helps anyone, we got the following to work in a file that references shared security settings:

```
components:
  securitySchemes:
    Basic_Authentication:
      $ref: 'https://your-public-url/auth.yml#/components/securitySchemes/Basic_Authentication'
```

and then defining

```
security:
  - Basic_Authentication: []
```
right before `paths:` .
