### ISSUE TITLE
How to define maximum occurrence as unbounded

### ISSUE THREAD

**Issue by oshu-sv** [OAI/OpenAPI-Specification#852]
Hi, How can i define the maximum occurrence of a parameter as unbounded?

```
 siteType:
    type: object
    properties:
      site:
        type: string
        minimum: 0
        maximum: unbounded
```

i would also like to know if there is an alternative oneOf for defining choice elements?

```
orderTypes:
    type: object
    required:
      - Number
    properties:    
      Number:
        type: string
      orderEquipment:
      orderProduct:
      orderItem:
```

So these three should be defined as choice elements:
orderEquipment:
orderProduct:
orderItem:

Thanks
