### ISSUE TITLE
Missing array.items declaration in templates

### ISSUE THREAD

**Issue by galaxie** [OAI/OpenAPI-Specification#865]
Hi, there.
I am trying to write a custom template based on java code generation.

I am going to use the following declaration in parameters section for some path:
```
      - name: geoID
        in: query
        description: Geo ID
        required: true
        type: array
        items:
          type: integer
          minimum: 12
```

then I generate code using `-l java` with debug option.

Here is what was generated to this parameter and so available in the template:

```
{
            "isQueryParam" : true,
            "hasMore" : true,
            "isContainer" : true,
            "secondaryParam" : true,
            "baseName" : "geoID",
            "paramName" : "geoID",
            "dataType" : "List<Integer>",
            "collectionFormat" : "csv",
            "description" : "GeoID",
            "baseType" : "Integer",
            "example" : "Arrays.asList(56)",
            "jsonSchema" : "{\n  \"name\" : \"geoID\",\n  \"in\" : \"query\",\n  \"description\" : \"GeoID\",\n  \"required\" : true,\n  \"type\" : \"array\",\n  \"items\" : {\n    \"type\" : \"integer\",\n    \"minimum\" : 12.0\n  }\n}",
            "isListContainer" : true,
            "isEnum" : false,
            "vendorExtensions" : { },
            "required" : true
 }
```

I don't see `minimum` property in the json result and so it's not available in my templates. Why is it so? Is it a bug or a feature?
