### ISSUE TITLE
Support for OAuth Flow Object with Host Templates Object

### ISSUE THREAD

**Issue by komikoni** [OAI/OpenAPI-Specification#885]
The "servers" parameter has multiple choices, and it has a template function in url.
In that case, OAuth authorizationUrl and tokenUrl should also be provided with multiple choices and template functions.

I think that the template function is common for authorizationUrl and tokenUrl.

```YAML
type: oauth2
flow: 
  implicit:
    authorizationUrl: https://{enviroment}.swagger.io/api/oauth/dialog
    templates:
      enviroment:
        enum:
          - test
          - prod
        default: test
    scopes:
      write:pets: modify pets in your account
      read:pets: read your pets
  authorizationCode:
    authorizationUrl: https://{enviroment}.swagger.io/api/oauth/dialog
    tokenUrl: https://{enviroment}.swagger.io/api/oauth/token
    templates:
      enviroment:
        enum:
          - test
          - prod
        default: test
    scopes:
      write:pets: modify pets in your account
      read:pets: read your pets 
```

What should I do with multiple choices?
