### ISSUE TITLE
can a parameter be used both for query and path?

### ISSUE THREAD

**Issue by seralf** [OAI/OpenAPI-Specification#965]
Hi, I'm trying to organize better my parameter definition.

Given two paths:

```
/example/{project}/api

/example/api?project={project}
```
I wonder if it's possible to maintain a single re-usable definition for a parameter wich can be used either as path parameter or query parameter.

My problem is that I have multiple endpoints which re-use the same parameters, and sometimes both the structures are present! Since the general definition is helpful (it allows me to define default values which can be used to suggest meaningful examples to test), I'd like to avoid a twin definition just to specify the type of a parameter...

at the moment I have something like:

```
...
parameters:
  project_path:
    name: project
    in: path
    type: string
    description: name of a project
    required: true
    default: my example project
  project_query:
    name: project
    in: query
    type: string
    description: name of a project
    required: true
    default: my example project
```
and I wish I'd have something like:

```
...
parameters:
  project_path:
    name: project
    in: 
     - path
     - query
    type: string
    description: name of a project
    required: true
    default: my example project
```

thanks in advance for any suggestion
