### ISSUE TITLE
Consider changing the enum type under Server Variable

### ISSUE THREAD

**Issue by webron** [OAI/OpenAPI-Specification#976]
Right now the type is an array of `primitive`. Variables are not typed, we were just looking to restrict values to non-complex objects. 

We can change it to `string` - which would simplify tooling. This will affect how the following example would be though:
```yaml
    port:
      enum:
        - 8443
        - 443
      default: 8443
```

That would become:
```yaml
    port:
      enum:
        - '8443'
        - '443'
      default: '8443'
```

which is a bit more annoying to write.

Changing the type of `enum` would also change the type of `default`.
